### ISSUE TITLE
*: MetricRelabelings feature KubeDB managed ServiceMonitors

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#1]
We have been cleaning up our metrics from prometheus and I found out that we are not able to define metricRelabelings for service monitor created by kubedb mysql. It would be great to have that feature.

E.g. in [bitnami mysql helm chart](https://github.com/bitnami/charts/tree/main/bitnami/mysql) you can see an implementation example. There is metrics.serviceMonitor.metricRelabelings value available which can be defined as follows:

```
metrics:
  serviceMonitor:
    metricRelabelings:
       - action: keep
         regex: (mysql_global_status_aborted_clients|....)
         sourceLabels:
           - __name__
```

So in your case the metricRelabelings should be definiable in here:

```
$ kubectl explain mysql.spec.monitor.prometheus.serviceMonitor
GROUP:      [kubedb.com](http://kubedb.com/)
KIND:       MySQL
VERSION:    v1alpha2

FIELD: serviceMonitor <Object>

DESCRIPTION:
    <empty>
FIELDS:
  interval      <string>
  labels        <map[string]string>
```

**Comment by tamalsaha** [comment]
Historically, we have avoided making the service monitor too customizable because I am worried the the MySQL crd will become an amalgamation of both MySQL and ServiceMonitor crds. What we have recommended users to do is this:

Create the MySQL crd with the monitoring agent "[prometheus.io](http://prometheus.io/)" instead of "[prometheus.io/operator](http://prometheus.io/operator)".
This will inject the prometheus exporter sidecar but not create the ServiceMonitor.
Then users can create the ServiceMonitor separately and use all the fields from the ServiceMonitor crd that they seem fit.

```yaml
apiVersion: kubedb.com/v1alpha2
kind: MySQL
metadata:
  name: coreos-prom-mysql
  namespace: demo
spec:
  version: "8.0.35"
  terminationPolicy: WipeOut
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: [prometheus.io](http://prometheus.io/)
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
```
