### ISSUE TITLE
Same name in cluster resource break kustomize build

### ISSUE THREAD

**Issue by cedvan** [kubedb/project#1024]
Hi,

Using same name in cluster resource break kustomize build with enable helm:

*kustomization.yaml*
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-namespace

helmCharts:
  - name: kubedb
    repo: https://charts.appscode.com/stable
    version: 2023.11.2
    namespace: my-namespace
    releaseName: kubedb
    valuesFile: config/kubedb.values.yaml
    includeCRDs: true
```

build with `kustomize build --enable-helm .`
Trigger error : 
```bash
Error: could not parse rnode slice into resource map: may not add resource with an already registered id: ClusterRole.v1.rbac.authorization.k8s.io/appscode:license-checker.[noNs]
```
