### ISSUE TITLE
'kubedb edit' command not working when version is a 'number'

### ISSUE THREAD

**Issue by the-redback** [kubedb/project#107]
When the version of the db can be converted in Number (say, Mysql:8.0), the original object takes the version as "8" (string) whereas Edited Object version is 8 (integer). 
So The program tries to change the version. As the cli program tries to forbid the changes made to version, it throws an error. 
```bash
A copy of your changes has been stored to "/tmp/kubedb-edit-llngz.yaml"
error: At least one of the following was changed:
	spec.version
	spec.storage
	spec.databaseSecret
	spec.nodeSelector
	spec.init
```
The details Log are below,

Original YAML:
```yaml
apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: m17
  namespace: demo
spec:
  version: 8.0
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  monitor:
    agent: coreos-prometheus-operator
    prometheus:
      port: 6529
      namespace: demo
      labels:
        app: kubedb
      interval: 10s
```

Debug :
```json
============================[ patch ]============================
{
   "metadata": {
      "clusterName": "",
      "deletionGracePeriodSeconds": null,
      "deletionTimestamp": null,
      "generation": 0,
      "initializers": null
   },
   "spec": {
      "doNotPause": true,
      "resources": null,
      "version": 8
   }
}


============================[ original json ]============================
{
   "apiVersion": "kubedb.com/v1alpha1",
   "kind": "MySQL",
   "metadata": {
      "creationTimestamp": "2018-01-12T04:56:33Z",
      "finalizers": [
         "kubedb.com"
      ],
      "name": "m17",
      "namespace": "demo",
      "resourceVersion": "75230",
      "selfLink": "/apis/kubedb.com/v1alpha1/namespaces/demo/mysqls/m17",
      "uid": "f5f30a05-f754-11e7-a5fc-08002723ac68"
   },
   "spec": {
      "databaseSecret": {
         "secretName": "m17-auth"
      },
      "monitor": {
         "agent": "coreos-prometheus-operator",
         "prometheus": {
            "interval": "10s",
            "labels": {
               "app": "kubedb"
            },
            "namespace": "demo",
            "port": 6529
         }
      },
      "resources": {},
      "storage": {
         "accessModes": [
            "ReadWriteOnce"
         ],
         "resources": {
            "requests": {
               "storage": "50Mi"
            }
         },
         "storageClassName": "standard"
      },
      "version": "8"
   },
   "status": {
      "creationTime": "2018-01-12T04:56:39Z",
      "phase": "Running"
   }
}

============================[ edited json ]============================
{
   "apiVersion": "kubedb.com/v1alpha1",
   "kind": "MySQL",
   "metadata": {
      "clusterName": "",
      "creationTimestamp": "2018-01-12T04:56:33Z",
      "deletionGracePeriodSeconds": null,
      "deletionTimestamp": null,
      "finalizers": [
         "kubedb.com"
      ],
      "generation": 0,
      "initializers": null,
      "name": "m17",
      "namespace": "demo",
      "resourceVersion": "75230",
      "selfLink": "/apis/kubedb.com/v1alpha1/namespaces/demo/mysqls/m17",
      "uid": "f5f30a05-f754-11e7-a5fc-08002723ac68"
   },
   "spec": {
      "databaseSecret": {
         "secretName": "m17-auth"
      },
      "doNotPause": true,
      "monitor": {
         "agent": "coreos-prometheus-operator",
         "prometheus": {
            "interval": "10s",
            "labels": {
               "app": "kubedb"
            },
            "namespace": "demo",
            "port": 6529
         }
      },
      "storage": {
         "accessModes": [
            "ReadWriteOnce"
         ],
         "resources": {
            "requests": {
               "storage": "50Mi"
            }
         },
         "storageClassName": "standard"
      },
      "version": 8
   },
   "status": {
      "creationTime": "2018-01-12T04:56:39Z",
      "phase": "Running"
   }
}

```
