### ISSUE TITLE
use separate resources & storage for individual node pool

### ISSUE THREAD

**Issue by aerokite** [kubedb/project#159]
ElasticSearch PVC can be allocated separately
ElasticSearch PVC can be allocated separately ，because master and client nodes do not need Storage as much as Data nodes，so master and client nodes need to set a smaller storage.
Please refer to ：
https://github.com/jetstack/navigator/blob/master/docs/quick-start/es-cluster-demo.yaml
such as:
```
apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
name: topology-es
namespace: demo
spec:
  nodePools:
  - name: master
    replicas: 3
    roles:
    - master
    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "1"
        memory: "3Gi"
    persistence:
      enabled: true
      size: 10Gi
      storageClass: standard
  - name: mixed
    replicas: 2
    roles:
    - data
    - ingest
    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "1"
        memory: "3Gi"
    persistence:
      enabled: true
      size: 10Gi
      storageClass: standard
```

Issue filed by @zhwenh  as pr https://github.com/kubedb/elasticsearch/pull/126
