### ISSUE TITLE
Feature: User should be able to specify db image with custom tag or versions

### ISSUE THREAD

**Issue by LinAnt** [kubedb/project#183]
A lot of users run postgres with certain extensions/add-ons that require a certain version of postgres or additional software bundled with the container.

To satisfy these requirements I suggest we make it possible to use own versions of the kubedb postgres image. i.e. kubedb/postgres:10.2-timescaledb0.9.2

**Comment by LinAnt** [comment]
PR https://github.com/kubedb/postgres/pull/148

**Comment by tamalsaha** [comment]
The proposal is to add a new crd called `<DB>Version` . This will be a non-namespaced crd . The official installer will create one for each supported DB version during installation.

Users can create their own variation/version with pre-built extensions and create a `<DB>Version` crd.

Then in the actual db crd `spec.version`, users use the name of the `<DB>Version` .

```
# created via installer
apiVersion: kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: 9.6 # non-namespaced
spec:
  version: 9.6 # postgres version
  db:
    image: kubedb/posrtgres: 9.6
  exporter:
    image: kubedb/posrtgres_exporter: 9.6
  tools:
    image: kubedb/posrtgres_tools: 9.6
---
# manually created by user
apiVersion: kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: tiemscaledb-9.6 # non-namespaced
spec:
  version: 9.6 # postgres version
  db:
    image: myco/timescale: 9.6
  exporter:
    image: myco/timescale_exporter: 9.6
  tools:
    image: myco/timescale_tools: 9.6
---
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: quick-postgres
  namespace: demo
spec:
  version: tiemscaledb-9.6 # 9.6
  doNotPause: true
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
```
