### ISSUE TITLE
Update resource on db CRD, does not update Statefulset

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#184]
Example: Elasticsearch

https://kubernetes.slack.com/archives/C8149MREV/p1529463492000043

**Comment by stormmore** [comment]
@tamalsaha I have a couple of other ES clusters that I will confirm this on.

Steps to reproduce:

# Create an ES cluster with no memor initial resources
# Check resources on ES statefulset
# Use kubedb edit to add memory resources
# Check resources on ES statefulset

**Comment by stormmore** [comment]
Pre-resource addition setting of ES_JAVA_OPTS var:

```
        - name: ES_JAVA_OPTS
          value: -Xms134217728 -Xmx134217728
```

Used `kubedb edit es apps-es -n prerc` to add resources, `128Mi` is 80% of `160Mi`:

```
  resources:
    limits:
      cpu: 100m
      memory: 160Mi
    requests:
      cpu: 50m
      memory: 160Mi
```

The output is "interesting":

```
$ kubedb edit es apps-es -n prerc                                                                                                               
<unknown> "apps-es" edited
```

Verified `kubectl get statefulset apps-es -o yaml` shows the update to the update resources:

```
- name: ES_JAVA_OPTS
  value: -Xms134217680 -Xmx134217680                                                                           │                                                                                                                             image: kubedb/elasticsearch:6.2
imagePullPolicy: IfNotPresent
name: elasticsearch
ports:
- containerPort: 9300
  name: transport
  protocol: TCP
- containerPort: 9200
  name: http
  protocol: TCP
resources:
  limits:
    cpu: 100m
    memory: 160Mi
  requests:
    cpu: 50m
    memory: 160Mi
```

At this point the cluster started cascade failing but the pods, per `kubectl get po`, did not show any restarts (https://github.com/kubedb/project/issues/185). Tweaking the resources , I couldn't get it to not crash, to the point that even removing the limits & requests still caused it fail.

Will all the modifications I have done to this ES instance, I only noticed the change didn't update the value is going from none to having resource requests and limits. 

That said, I also found that when it did change ES_JAVA_OPTS was based on the requests not limits, is that what you expect, or should it be the other way around?
