### ISSUE TITLE
Storage targets dynamic prefix

### ISSUE THREAD

**Issue by boxedcode** [kubedb/project#243]
With the snapshot feature, is it possible to have a dynamic prefix for the storage targets that support a prefix. For example, with the S3 storage target, you can define the spec like this:

```
s3:
    endpoint: 's3.amazonaws.com'
    bucket: kubedb-qa
    prefix: demo
```

So instead of having a fixed prefix like ```demo``` above, the prefix will be based on the date that the snapshot is being taken, maybe using a customisable prefix template or fixed prefix template options e.g.:

```
s3:
    endpoint: 's3.amazonaws.com'
    bucket: kubedb-qa
    prefixType: date
    prefix: YYYY/MM/dd
```

OR

```
s3:
    endpoint: 's3.amazonaws.com'
    bucket: kubedb-qa
    prefix: template_date
```

What are your thoughts on the above?
