### ISSUE TITLE
Fix point in time recovery (PITR) for Postgres

### ISSUE THREAD

**Issue by soosap** [kubedb/project#254]
**Replicate**

**Step 1**: I deploy the following `Postgres` workload

```yaml
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: registry-postgres
  namespace: default
  labels:
    app: postgres
    chart: "postgres-0.1.0"
    release: registry
    heritage: Tiller
spec:
  version: "10.2"
  replicas: 1
  doNotPause: True
  databaseSecret:
    secretName: registry-postgres
  storage:
    storageClassName: aws-ebs-gp2
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  archiver:
    storage:
      storageSecretName: s3-secret
      s3:
        endpoint: s3.amazonaws.com
        bucket: my-backup-bucket
  init:
    postgresWAL:
      storageSecretName: s3-secret
      s3:
        endpoint: s3.amazonaws.com
        bucket: my-backup-bucket
        prefix: "kubedb/default/registry-postgres/archive"
      pitr: latest # <==============================
serviceTemplate:
  metadata:
    name: registry-postgres
    namespace: default
    labels:
      app: postgres
      chart: "postgres-0.1.0"
      release: registry
      heritage: Tiller
  spec:
    type: ClusterIP
```
The database runs without problems. Postgres WAL and basebackup files are created into the S3 bucket.

**Step 2**: I work with the database and mess it up at some point. I want to go back 2h in time.

```sh
$ kubectl patch -n default pg/registry-postgres -p '{"spec":{"doNotPause":false}}' --type="merge"

$ kubectl delete -n default pg/registry-postgres
```
I first delete the postgres instance or in other words put it into a "dormant" state.

I then try to recreate the `Postgres` workload using the following yaml:
```yaml
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: registry-postgres
  namespace: default
  labels:
    app: postgres
    chart: "postgres-0.1.0"
    release: registry
    heritage: Tiller
spec:
  version: "10.2"
  replicas: 1
  doNotPause: True
  databaseSecret:
    secretName: registry-postgres
  storage:
    storageClassName: aws-ebs-gp2
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  archiver:
    storage:
      storageSecretName: s3-secret
      s3:
        endpoint: s3.amazonaws.com
        bucket: my-backup-bucket
  init:
    postgresWAL:
      storageSecretName: s3-secret
      s3:
        endpoint: s3.amazonaws.com
        bucket: my-backup-bucket
        prefix: "kubedb/default/registry-postgres/archive"
      pitr: 2018-08-29 20:00:00 CET # <==============================
serviceTemplate:
  metadata:
    name: registry-postgres
    namespace: default
    labels:
      app: postgres
      chart: "postgres-0.1.0"
      release: registry
      heritage: Tiller
  spec:
    type: ClusterIP
```
**Expected**
Postgres database starts and puts it into the state which existed at the `pitr` time in point.

**Actual**
I receive the following error when trying to deploy the above workload:
```
Error: release registry failed: Internal error occurred: admission webhook "postgres.mutators.kubedb.com" denied the request: postgres spec mismatches with OriginSpec in DormantDatabases. Diff: {*v1alpha1.PostgresSpec}.Init.PostgresWAL.PITR:
	-: "latest"
	+: "2018-08-29 20:00:00 CET"
```
