### ISSUE TITLE
Take backup  and restore of particular database from mysql-server  

### ISSUE THREAD

**Issue by JJSWAIN2018** [kubedb/project#256]
Can you please concentrate to take backup and restore of particular databases instead of all mysql server .

**Comment by tamalsaha** [comment]
Yes. We plan to support this.

**Comment by the-redback** [comment]
Fixed in https://github.com/kubedb/mysql/pull/93. Now snapshots can have PodTemplate where user can specify extra arguments, i.e.

```
apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: snap-mysql-infant
  namespace: demo
  labels:
    kubedb.com/kind: MySQL
spec:
  databaseName: mysql-infant
  storageSecretName: my-snap-secret
  gcs:
    bucket: kubedb
  podTemplate:
    spec:
      args:
      - "db_name"
```
