### ISSUE TITLE
Update docs: Fix Snapshot backend 

### ISSUE THREAD

**Issue by hossainemruz** [kubedb/project#266]
**Wrong backend format:**
```
local:
  mountPath: /repo
  volumeSource:
    persistentVolumeClaim:
      claimName: task-pv-claim
```
**Right backend format:**
```
local:
  mountPath: /repo
  persistentVolumeClaim:
    claimName: task-pv-claim
```
Ref: https://github.com/kubedb/project/issues/265#issuecomment-418755176
