### ISSUE TITLE
Resource requests and limits are not applied to init containers

### ISSUE THREAD

**Issue by jwalker343** [kubedb/project#311]
## Description
When you have a ResourceQuota applied to a namespace it sets a requirement that every pod must specify the relevant resources, otherwise the pod will not be scheduled.

> If quota is enabled in a namespace for compute resources like cpu and memory, users must specify requests or limits for those values; otherwise, the quota system may reject pod creation
https://kubernetes.io/docs/concepts/policy/resource-quotas/

When creating a new mysql database, the spec currently allows users to specify the resource requests which are passed through to the statefulset and configured for the mysql container, but not the init container. Since there are no resource requests or limits specified for the init container the admission controller prevents the pod from being scheduled and pod creation fails.

## To reproduce this issue:

Enable ResourceQuotas on a namespace:
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-request-limits
  namespace: demo
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "4Gi"
```

Create mysql Object
```
apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysqldatabase
  namespace: demo
spec:
  version: "8.0"
  replicas: 1
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
  doNotPause: true
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
```

Observe no running pods and statefulset not initializing:
```
kubectl get pods
No resources found.

kubectl get statefulset
NAME            DESIRED   CURRENT   AGE
mysqldatabase   1         0         4m
```

Observe the events in the namespace, to identify the error
```
kubectl get events -n demo
LAST SEEN   FIRST SEEN   COUNT     NAME                                    KIND                    SUBOBJECT   TYPE      REASON                  SOURCE                        MESSAGE
2m          2m           1         data-mysqldatabase-0.155bbd5d88cd33bf   PersistentVolumeClaim               Normal    ProvisioningSucceeded   persistentvolume-controller   Successfully provisioned volume pvc-f6266c11-cb3b-11e8-b90a-42010a8e0042 using kubernetes.io/gce-pd
2m          2m           1         mysqldatabase.155bbd5c85a7a450          MySQL                               Normal    Successful              MySQL operator                Successfully created Service
2m          2m           1         mysqldatabase.155bbd5c88de54cd          StatefulSet                         Normal    SuccessfulCreate        statefulset-controller        create Claim data-mysqldatabase-0 Pod mysqldatabase-0 in StatefulSet mysqldatabase success
21s         2m           20        mysqldatabase.155bbd5c891d9336          StatefulSet                         Warning   FailedCreate            statefulset-controller        create Pod mysqldatabase-0 in StatefulSet mysqldatabase failed error: pods "mysqldatabase-0" is forbidden: failed quota: resource-request-limits: must specify requests.cpu,requests.memory

```

## Resolving the issue

Editing the statefulset and adding the resources to the init container immediately causes the pod to be scheduled:

```
kubectl edit statefulset

initContainers:
- command:
  - rm
  - -rf
  - /var/lib/mysql/lost+found
  image: busybox
  imagePullPolicy: IfNotPresent
  name: remove-lost-found
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

statefulset "mysqldatabase" edited
```

Observe that the pods are scheduled and run accordingly. 

```
kubectl get statefulset
NAME            DESIRED   CURRENT   AGE
mysqldatabase   1         1         10m

kubectl get pods
NAME              READY     STATUS     RESTARTS   AGE
mysqldatabase-0   0/1       Init:0/1   0          9s

kubectl get pods
NAME              READY     STATUS    RESTARTS   AGE
mysqldatabase-0   1/1       Running   0          3m
```
