### ISSUE TITLE
Failed to create snapshot resource

### ISSUE THREAD

**Issue by Mahmoud-Mardeni** [kubedb/project#313]
Whenever I try to run the command to create a snapshot resource using kubectl I got the following error:

Error from server (InternalError): error when creating "local-snapshot.yaml": Internal error occurred: failed calling admission webhook "snapshot.mutators.kubedb.com": the server could not find the requested resource

**Comment by hossainemruz** [comment]
@Mahmoud-Mardeni I think you are facing this issue https://github.com/kubedb/project/issues/260

**Comment by Mahmoud-Mardeni** [comment]
@hossainemruz Can you tell me how can I apply that fix. Thanks

**Comment by hossainemruz** [comment]
@Mahmoud-Mardeni which KubeDB version are you using? This has been fixed in 0.9.x.

**Comment by Mahmoud-Mardeni** [comment]
0.8.0

**Comment by hossainemruz** [comment]
Ok @Mahmoud-Mardeni. It has been fix on 0.9.x. You won't face this on newer version. However, if you want to stick with 0.8.0, I can suggest a workaround.

Please show output of this command

```
kubectl get mutatingwebhookconfiguration mutators.kubedb.com -o yaml
```

**Comment by Mahmoud-Mardeni** [comment]
@hossainemruz Thanks, I have upgraded to 0.9 version and the problem is solved but when I run the following command:

` kubedb get snap -n mysql-db local-snapshot -o yaml`

I got the following output:

status:
  completionTime: 2018-10-14T10:35:40Z
  phase: Failed
  reason: One Snapshot is already Running
  startTime: 2018-10-14T10:35:40Z

**Comment by hossainemruz** [comment]
So there is already a snapshot that is not finished yet...
Check if there are any,
```
kubectl get snapshots -n mysql-db
```
what is the output of following command?
```
kubedb describe my -n mysql-db <your mysql crd name>
```

**Comment by Mahmoud-Mardeni** [comment]
Here is the output:

`kubectl get snapshots -n mysql-db`

NAMESPACE   NAME             DATABASE      STATUS    AGE
mysql-db    local-snapshot   my/mysql-db   Unknown   3m

`kubedb describe my -n mysql-db <your mysql crd name>`

  FirstSeen   LastSeen   Count     From             Type       Reason              Message
  ---------   --------   -----     ----             --------   ------              -------
  34s         34s        1         Job Controller   Warning    SnapshotFailed      Failed to complete snapshot
  1m          1m         1         Job Controller   Normal     Starting            Backup running

**Comment by Mahmoud-Mardeni** [comment]
```
Name:           mysql-db
Namespace:      mysql-db
StartTimestamp: Wed, 01 Aug 2018 19:34:25 +0300
Replicas:       1  total
Status:         Running
Volume:
  StorageClass: do-block-storage
  Capacity:     10Gi
  Access Modes: RWO

StatefulSet:
  Name:                 mysql-db
  Replicas:             1 current / 1 desired
  CreationTimestamp:    Wed, 01 Aug 2018 19:34:25 +0300
  Pods Status:          1 Running / 0 Waiting / 0 Succeeded / 0 Failed

Service:
  Name:         mysql-db
  Type:         ClusterIP
  IP:           10.3.0.48
  Port:         db      3306/TCP

Database Secret:
  Name: mysql-secret
  Type: Opaque
  Data
  ====
  password:     16 bytes
  user:         4 bytes

Snapshots:
  Name             Bucket                       StartTime                         CompletionTime                    Phase
  ----             ------                       ---------                         --------------                    -----
  local-snapshot   local:/var/mysql-snapshots   Sun, 14 Oct 2018 14:25:52 +0300   Sun, 14 Oct 2018 14:26:10 +0300   Failed

Events:
  FirstSeen   LastSeen   Count     From             Type       Reason              Message
  ---------   --------   -----     ----             --------   ------              -------
  19s         19s        1         Job Controller   Warning    SnapshotFailed      Failed to complete snapshot
  37s         37s        1         Job Controller   Normal     Starting            Backup running
  1m          1m         1         Job Controller   Normal     SuccessfulWipeOut   Successfully wiped out Snapshot: local-snapshot
  1m          1m         1         Job Controller   Normal     WipingOut           Wiping out Snapshot: local-snapshot
```

**Comment by hossainemruz** [comment]
can you share the snapshot yaml?

**Comment by Mahmoud-Mardeni** [comment]
Here is my snapshot yaml:
```
apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: local-snapshot
  namespace: mysql-db
  labels:
    kubedb.com/kind: MySQL
spec:
  databaseName: mysql-db
  local:
    mountPath: /var/mysql-snapshots
    volumeSource:
      hostPath: 
          # directory location on host
          path: /var/mysql-snapshots
          # this field is optional
          type: DirectoryOrCreate
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
```

**Comment by hossainemruz** [comment]
ok. You don't have to specify `volumeSource:` the documentation is not updated.
Look at this issue: https://github.com/kubedb/project/issues/266
Try this yaml.
```
apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: local-snapshot
  namespace: mysql-db
  labels:
    kubedb.com/kind: MySQL
spec:
  databaseName: mysql-db
  local:
    mountPath: /var/mysql-snapshots
    hostPath: 
      # directory location on host
      path: /var/mysql-snapshots
      # this field is optional
      type: DirectoryOrCreate
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
```

**Comment by Mahmoud-Mardeni** [comment]
Ok, I think we are done the backup is running now.

Thanks, Appreciate your work guys.

**Comment by hossainemruz** [comment]
Cool. Closing the issue. Feel free to reopen if you face any further error.

**Comment by Mahmoud-Mardeni** [comment]
@hossainemruz Yes but in failed status, I have deleted it and create it again. Here is the output:
```

kubedb describe my -n mysql-db mysql-db
Name:           mysql-db
Namespace:      mysql-db
StartTimestamp: Wed, 01 Aug 2018 19:34:25 +0300
Replicas:       1  total
Status:         Running
Volume:
  StorageClass: do-block-storage
  Capacity:     10Gi
  Access Modes: RWO

StatefulSet:
  Name:                 mysql-db
  Replicas:             1 current / 1 desired
  CreationTimestamp:    Wed, 01 Aug 2018 19:34:25 +0300
  Pods Status:          1 Running / 0 Waiting / 0 Succeeded / 0 Failed

Service:
  Name:         mysql-db
  Type:         ClusterIP
  IP:           10.3.0.48
  Port:         db      3306/TCP

Database Secret:
  Name: mysql-secret
  Type: Opaque
  Data
  ====
  password:     16 bytes
  user:         4 bytes

Snapshots:
  Name             Bucket                       StartTime                         CompletionTime                    Phase
  ----             ------                       ---------                         --------------                    -----
  local-snapshot   local:/var/mysql-snapshots   Sun, 14 Oct 2018 16:33:12 +0300   Sun, 14 Oct 2018 16:33:42 +0300   Failed

Events:
  FirstSeen   LastSeen   Count     From             Type       Reason           Message
  ---------   --------   -----     ----             --------   ------           -------
  1m          1m         1         Job Controller   Warning    SnapshotFailed   Failed to complete snapshot
  2m          2m         1         Job Controller   Normal     Starting         Backup running

```

**Comment by Mahmoud-Mardeni** [comment]
I have recreate it and again its stuck in running phase for more than 6 mins.

Ps: The size of entire dbs running on that instance is only ~7MB.

**Comment by hossainemruz** [comment]
@Mahmoud-Mardeni can you share yaml of job?

**Comment by Mahmoud-Mardeni** [comment]
```
apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: local-snapshot
  namespace: mysql-db
  labels:
    kubedb.com/kind: MySQL
spec:
  databaseName: mysql-db
  local:
    mountPath: /var/mysql-snapshots
    hostPath: 
          # directory location on host
          path: /var/mysql-snapshots
          # this field is optional
          type: DirectoryOrCreate
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
```

**Comment by hossainemruz** [comment]
@Mahmoud-Mardeni I asked for Job's yaml.
```
kubectl get job -n <namespace> -o yaml
```

**Comment by hossainemruz** [comment]
@Mahmoud-Mardeni are you using custom secret for MySQL? Can you share MySQL crd yaml?

**Comment by Mahmoud-Mardeni** [comment]
```
apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysql-db
  namespace: mysql-db
spec:
  version: "5.7"
  databaseSecret:
    secretName: mysql-secret
  doNotPause: true
  storage:
    storageClassName: "do-block-storage"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  imagePullSecrets:
    - name: regcred
```
