### ISSUE TITLE
Add doc explaining how to perform  point-in-time-recovery (PITR) in Postgres

### ISSUE THREAD

**Issue by hossainemruz** [kubedb/project#317]

**Comment by hossainemruz** [comment]
**Sample YAML:**
```yaml
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: replay-postgres
  namespace: demo
spec:
  version: "10.2-v1"
  databaseSecret:
    secretName: p1-auth
  terminationPolicy: Delete
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  init:
    postgresWAL:
      storageSecretName: s3-secret
      s3:
        bucket: kubedb
        prefix: 'kubedb/demo/wal-postgres/archive'
      pitr:
        targetTime: "2018-10-14 08:41:00 UTC"
```

**Available PITR options:**
https://github.com/kubedb/apimachinery/blob/7d6ac75d29a6f7c7adfec09c056043c913807c01/apis/kubedb/v1alpha1/postgres_types.go#L174
