### ISSUE TITLE
Postgres: All pod works as replica after Node/Cluster restart

### ISSUE THREAD

**Issue by hossainemruz** [kubedb/project#330]
**From Slack:** All pods of a Postgres cluster work as replica after a Node/Cluster restart. Leader election fail to elect master node. Issue persist on both 0.8.0 and 0.9.0-rc.0.

Postgres Cluster:
```
# This is the database itself
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: "elab-database"
spec:
  version: "9.6"
  replicas: 3
  standbyMode: hot
  doNotPause: true
  storage:
    storageClassName: "ceph-block"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "10Gi"

  backupSchedule:
    cronExpression: "@every 24h"
    local:
      path: /backup
      volumeSource:
        persistentVolumeClaim: "elab-database-backup-pvc"

```
**Ref:** https://kubernetes.slack.com/archives/C8149MREV/p1540494279000100
