### ISSUE TITLE
[MongoDB snapshot] Wrong adresses

### ISSUE THREAD

**Issue by oxyno-zeta** [kubedb/project#342]
Hello,

I'm using KubeDB 0.9.0-rc0 with MongoDB 3.6-v1 and I enabled the backup schedule feature. But unfortunately, it doesn't work... The host variable in the kind job manifest is wrong. I don't know why.

Here is the value:
```
- --host=rs0/mongo-replicaset-0.mongo-replicaset-gvr.svc,mongo-replicaset-1mongo-replicaset-gvr.svc,mongo-replicaset-2mongo-replicaset-gvr.svc
```
There is no dot after replicaset-1 and replicaset-2.

Here is my manifests:
KubeDB:
```
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mongo-replicaset
spec:
  version: "3.6-v1"
  replicas: 3
  replicaSet:
    name: rs0
  storage:
    storageClassName: "local-storage"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  monitor:
    agent: prometheus.io/builtin
  backupSchedule:
    cronExpression: "@every 24h"
    storageSecretName: mgo-snap-secret
    s3:
      endpoint: "s3.amazonaws.com"
      bucket: "mybucket"
      prefix: mongodb
```

I've created a snapshot manifest too:
```
apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  clusterName: ""
  finalizers:
  - kubedb.com
  generation: 1
  labels:
    kubedb.com/kind: MongoDB
    kubedb.com/name: mongo-replicaset
  name: mongo-replicaset-manual
  namespace: default
spec:
  databaseName: mongo-replicaset
  podTemplate:
    controller: {}
    metadata: {}
    spec:
      resources: {}
  s3:
    bucket: mybucket
    endpoint: s3.amazonaws.com
    prefix: mongodb
  storageSecretName: mgo-snap-secret
```

There are the log of the backup pod:
```
rs0/mongo-replicaset-0.mongo-replicaset-gvr.svc,mongo-replicaset-1mongo-replicaset-gvr.svc,mongo-replicaset-2mongo-replicaset-gvr.svc: forward host lookup failed: Unknown host
Waiting... database is not ready yet
rs0/mongo-replicaset-0.mongo-replicaset-gvr.svc,mongo-replicaset-1mongo-replicaset-gvr.svc,mongo-replicaset-2mongo-replicaset-gvr.svc: forward host lookup failed: Unknown host
Waiting... database is not ready yet

```

Can you help me with this ?

EDIT: The problem is in this file:
https://github.com/kubedb/apimachinery/blob/master/apis/kubedb/v1alpha1/mongodb_helpers.go
At line 70, I found:
```
host += "," + m.Name + "-" + strconv.Itoa(i) + m.GoverningServiceName() + "." + m.Namespace + ".svc"
```
It should be:
```
host += "," + m.Name + "-" + strconv.Itoa(i) + "." + m.GoverningServiceName() + "." + m.Namespace + ".svc"
```

EDIT 2: I've created a pull request for that: https://github.com/kubedb/apimachinery/pull/358

Thanks !
