### ISSUE TITLE
MySQL CrashLoopBackOff "--initialize specified but the data directory has files in it. Aborting."

### ISSUE THREAD

**Issue by mauritsvdvijgh** [kubedb/project#365]
### Summary
MySQL pod is stuck in CrashLoopBackOff after:
1. Installing the kubedb operator version 0.9.0 using the installation script
2. applying: https://raw.githubusercontent.com/kubedb/cli/0.9.0/docs/examples/mysql/quickstart/demo-2.yaml changing only the storage class name. (tried 8.0-v1 and 8-v1)

### Detailed description
After installing kubedb 0.9.0 through the `kubedb.sh` installation script and applying the following yaml:

```
metadata:
  name: mysql-quickstart
  namespace: demo
spec:
  version: "8-v1"
  storageType: Durable
  storage:
    storageClassName: "rook-ceph-block"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  terminationPolicy: DoNotTerminate
```

A pod is created that is stuck in CrashLoopBackOff:

```
Name:               mysql-quickstart-0
Namespace:          demo
Priority:           0
PriorityClassName:  <none>
Start Time:         Tue, 18 Dec 2018 08:56:52 +0100
Labels:             controller-revision-hash=mysql-quickstart-66bb58c45c
                    kubedb.com/kind=MySQL
                    kubedb.com/name=mysql-quickstart
                    statefulset.kubernetes.io/pod-name=mysql-quickstart-0
Annotations:        cni.projectcalico.org/podIP: 10.42.2.10/32
Status:             Running
IP:                 10.42.2.10
Controlled By:      StatefulSet/mysql-quickstart
Init Containers:
  remove-lost-found:
    Container ID:  docker://0341d2a4c9b3a03a16d06893dbe0d0c9c9445e03faeaffdaafb48385d4c7ba4d
    Image:         busybox
    Image ID:      docker-pullable://busybox@sha256:2a03a6059f21e150ae84b0973863609494aad70f0a80eaeb64bddd8d92465812
    Port:          <none>
    Host Port:     <none>
    Command:
      rm
      -rf
      /var/lib/mysql/lost+found
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 18 Dec 2018 08:57:00 +0100
      Finished:     Tue, 18 Dec 2018 08:57:00 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/lib/mysql from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8x8pv (ro)
Containers:
  mysql:
    Container ID:   docker://cf02746821183903a7c348a6cfb4e15763c79685bbda06592273a3d27c51348d
    Image:          kubedb/mysql:8-v1
    Image ID:       docker-pullable://kubedb/mysql@sha256:66ece2d6799baa61b65977a6679d612a2e96d4abc890305d2a03441e7e80f8ad
    Port:           3306/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 18 Dec 2018 08:57:33 +0100
      Finished:     Tue, 18 Dec 2018 08:57:33 +0100
    Ready:          False
    Restart Count:  2
    Environment:
      MYSQL_ROOT_PASSWORD:  <set to the key 'password' in secret 'mysql-quickstart-auth'>  Optional: false
      MYSQL_ROOT_USERNAME:  <set to the key 'username' in secret 'mysql-quickstart-auth'>  Optional: false
    Mounts:
      /var/lib/mysql from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8x8pv (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-mysql-quickstart-0
    ReadOnly:   false
  default-token-8x8pv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-8x8pv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  55s (x12 over 59s)  default-scheduler  pod has unbound PersistentVolumeClaims (repeated 5 times)
  Normal   Scheduled         53s                 default-scheduler  Successfully assigned demo/mysql-quickstart-0 to sv9
  Normal   Pulled            47s                 kubelet, sv9       Container image "busybox" already present on machine
  Normal   Created           45s                 kubelet, sv9       Created container
  Normal   Started           44s                 kubelet, sv9       Started container
  Normal   Pulling           42s                 kubelet, sv9       pulling image "kubedb/mysql:8-v1"
  Normal   Pulled            41s                 kubelet, sv9       Successfully pulled image "kubedb/mysql:8-v1"
  Normal   Pulled            14s (x2 over 35s)   kubelet, sv9       Container image "kubedb/mysql:8-v1" already present on machine
  Normal   Created           13s (x3 over 40s)   kubelet, sv9       Created container
  Normal   Started           12s (x3 over 40s)   kubelet, sv9       Started container
  Warning  BackOff           10s (x4 over 31s)   kubelet, sv9       Back-off restarting failed container
```

Logs of the pod:

```
$ kubectl logs mysql-quickstart-0
Initializing database
2018-12-18T07:57:33.220872Z 0 [Note] Basedir set to /usr/
2018-12-18T07:57:33.221132Z 0 [Warning] The syntax '--symbolic-links/-s' is deprecated and will be removed in a future release
2018-12-18T07:57:33.222515Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2018-12-18T07:57:33.222561Z 0 [ERROR] Aborting
```

Reinstalling kubedb, creating the MySQL resource again making sure the pv/pvc is gone and deleting the pod did not seem to work.

```
$ kubectl delete mysql --all
mysql.kubedb.com "mysql-quickstart" deleted
```

Took a few minutes but worked after a while.

Spinned up a pod with alpine as the image, mounted the pv in there and got a shell:
```
/mnt/pv # ls -alh
total 12299
drwxr-xr-x    2 999      ping        1.0K Dec 18 09:10 .
drwxr-xr-x    1 root     root        4.0K Dec 18 09:20 ..
-rw-r-----    1 999      ping       12.0M Dec 18 07:57 ibdata1

# remove all the files on the pv for mysql
/mnt/pv # rm -rf *
```

After removing the files, deleting the alpine pod:

```
$ kubectl apply -f demo-2.yaml
mysql.kubedb.com/mysql-quickstart created

$ kubectl describe pods
...
  Warning  BackOff    4s (x2 over 18s)  kubelet, sv10      Back-off restarting failed container
...

$ kubectl logs -f mysql-quickstart-0
Initializing database
2018-12-18T09:24:38.812267Z 0 [Note] Basedir set to /usr/
2018-12-18T09:24:38.812580Z 0 [Warning] The syntax '--symbolic-links/-s' is deprecated and will be removed in a future release
2018-12-18T09:24:38.813992Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2018-12-18T09:24:38.814043Z 0 [ERROR] Aborting
```

Same problem.

For context, applying the following Postgres resource worked correctly:
```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: post-quickstart
  namespace: demo
spec:
  version: "10.2-v1"
  storageType: Durable
  storage:
    storageClassName: rook-ceph-block
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
terminationPolicy: DoNotTerminate
```

**Comment by the-redback** [comment]
I tried it myself in `rook-ceph-block` storageclass. Faced the same problem. But it worked after increasing the storage size. In my case, the following is working. Can you verify?

```yaml
apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysql-quickstart
  namespace: demo
spec:
  version: "8-v1"
  storageType: Durable
  storage:
    storageClassName: "rook-ceph-block"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate
```
