### ISSUE TITLE
Disaster recovery

### ISSUE THREAD

**Issue by endrec** [kubedb/project#368]
I need to recreate databases from a different cluster.

As of kubedb 0.9.0, there is no easy way to achieve this:
- it's not possible to create a Snapshot resource for a non-existent database
- if you create a db, so you can create a Snapshot (in Succeeded state), you can't initialise that db from the snapshot, because the admission webhook denies the request to change `spec.init`

Ideally, I would like to specify a Snapshot template in `spec.init`, and the operator automatically would create a Snapshot resource from the latest snapshot, and initialize the db from that.
Something like

```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: recovered-postgres
  namespace: demo
spec:
  version: "9.6-v1"
  databaseSecret:
    secretName: script-postgres-auth
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  init:
    snapshotSource:
        #name: instant-snapshot ## Optional, if omitted, the latest snapshot will be used
        #namespace: demo        ## Optional, defaults to the namespace of the database
        spec: 
          storageSecretName: s3-secret
          s3:
            endpoint: 's3.amazonaws.com'
            bucket: kubedb
            prefix: demo
```

**Comment by endrec** [comment]
Discussion on slack: https://kubernetes.slack.com/archives/C8149MREV/p1545138216241300

**Comment by hossainemruz** [comment]
In case of disaster or to restore a db from Snapshot in a new cluster, we won't have the respective Snapshot crd. So, we have to create it manually.

Recovery flow should be:
1. Install KubeDB in the new cluster.
2. Create Snapshot crd manually.
3. Create database crd with init section configured to initialize from the Snapshot.

**Problem-1:**
Creating Snapshot manually in step 2 will not succeed. KubeDB validator will reject to create the Snapshot as respective database does not exist.

**Temporary Workaround of Problem-1:**
A temporary workaround for problem-1 can be disabling Snapshot validator temporarily.

To disable Snapshot validator edit `validators.kubedb.com` `validatingwebhookconfiguration` and remove or modify `snapshot.validators.kubedb.com` section.

Example:
```
kubectl edit validatingwebhookconfiguration validators.kubedb.com
```
Then, change
```
 resources:
   - snapshots
```
to something invalid. i.e.
```
 resources:
   - snapshots-disabled
```
Then create the Snapshot. Once, the Snapshot is created, enable the webhook again.

**Problem-2:**
If we can solve `Problem-1` we will hit another problem. When we will create a Snapshot crd, KubeDB will try to backup the respective database and will cause error as the database does not exist.

**Temporary Workaround of Problem-2:**
KubeDB does not process andy `Succeeded` or `Failed` Snapshot. So, we can create the Snapshot by setting `status.phase: Succeeded`.

Example:
```yaml
apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: instant-snapshot
  namespace: demo
  labels:
    kubedb.com/kind: Elasticsearch
spec:
  databaseName: es-demo
  s3:
    endpoint: 's3.amazonaws.com'
    bucket: kubedb
    prefix: demo
status:
  phase: Succeeded
```

However, none of the workaround are not expected and hard to automate. We should have native support for this use case.

**Comment by bodewig** [comment]
The workaround for **Problem2** doesn't work for me, I still end up with a snapshot in a "Failed" state. This is kubedb 0.10.0 on Azure Kubernetes Services. This doesn't seem to prevent a restore of the snapshot, though, so maybe the workaround isn't required at all.

**Comment by zetaab** [comment]
Okay here is what I did:

1) created new database with name `quick-postgres` to new cluster. Took empty snapshot from it with name `instant-snapshot`. It created empty snapshot fine and it succeeded. File is available in S3
2) created snapshot in old cluster in old database with name `instant-snapshot` it overwrites the empty snapshot file
3) Modified new cluster `quick-postgres` terminationPolicy to `DormantDatabase` and deleted the database using `kubectl delete postgres quick-postgres`. 

After this we are in situation that we have working snapshot in new cluster, and also sql dump is available in S3 in correct path.

4) restore from snapshot like usually

Example
```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: quick-postgres
  namespace: foobar
spec:
  version: "11.1"
  storageType: Durable
  replicas: 3
  databaseSecret:
    secretName: quick-postgres-auth
  storage:
    storageClassName: "csi-sc-cinderplugin"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
  terminationPolicy: DoNotTerminate
  init:
    snapshotSource:
      name: instant-snapshot
      namespace: foobar
```

And Tadaa! your database is moved from cluster to another. However, this is not perfect way if your old cluster is broken!
