### ISSUE TITLE
Deleting one instant-snapshot deletes them all from storage

### ISSUE THREAD

**Issue by johnraz** [kubedb/project#377]
I was evaluating kubedb's snapshot feature today with postgresql, following the guide at: https://kubedb.com/docs/0.9.0/guides/postgres/snapshot/instant_backup/

Instead of creating only one instant snapshot, I created 2 of them:

```
instant-snapshot
instant-snapshot-2
```

I did this by reusing the below resource definition and only changed the name metadata.

```
apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: <the-name>
  namespace: kubedb-test
  labels:
    kubedb.com/kind: Postgres
spec:
  databaseName: script-postgres
  storageSecretName: gcs-secret
  gcs:
    bucket: kubedb-test
```

I could then see the 2 folders + sql files appear in my GCS bucket 🎉 

I was happy and decided to try to delete one of the snapshot so I ran:

```
kubectl delete snap -n kubedb-test instant-snapshot
snapshot.kubedb.com "instant-snapshot" deleted
```

I looked at the GCS bucket again to find out everything has been deleted from the bucket...
No subfolders, no nothing anymore, only the bucket was there 😱.

Checking the snapshot resources, the `instant-snapshot-2` is still around:
```
kubedb get snap --namespace kubedb-test
NAME                 DATABASENAME      STATUS      AGE
instant-snapshot-2   script-postgres   Succeeded   3m
```

I think this is pretty bad as I obvioulsy only expected the one snapshot I deleted to be removed and not the other one.

Did I miss something in the way this is supposed to work or is it an actual bug?

Thanks already and for the record my experience with the project appart from this glitch has been super smooth so far.
