### ISSUE TITLE
Support initializing a PG database from a snapshot in a different namespace 

### ISSUE THREAD

**Issue by dmarkey** [kubedb/project#379]
So I made a snapshot of a DB in one namespace and tried to create a new DB in a separate namespace. The DBs come up OK but the jobs to restore job fails, looking for 
 MountVolume.SetUp failed for volume "osmconfig" : secrets "osm-mysnapl" not found

I do see these in the original namespace however.

Latest version.

**Comment by tamalsaha** [comment]
This is not currently possible, since we don't allow selecting Snapshot from a different namespace. To work around, you can manually copy the Snapshot object and it's associated secret to the desired namespace and then use that Snapshot.

**Comment by GeertJohan** [comment]
I could really use this feature as well. I'll describe my use-case, perhaps it could help add rationale and or design decisions.

I run multiple namespaces for different environments of an application. test, staging, production.The test and staging environments are deployed multiple times a day, during which the database contents must be reset. Each application is also duplicated for each 'brand', so there are about 6 namespaces currently running their own postgres instance.

A script during deployment writes a pg dump / sql commands, like this: `cat file.sql | kubectl exec ... psql ..`. The script is performed from outside the cluster, so even a small db of 3GB takes a long time to restore as all SQL commands and data are sent over the line. I have a snapshot with the data, but it's in a single namespace and cannot be shared to other namespaces. The main problem seems to be the secret, which is not allowed to be shared across namespaces.

I prefer to use a volume for snapshotting, as I didn't get snapshotting to Swift to work properly yet.

**Comment by gobengo** [comment]
I'd like this too, but with MySQL.

At least some documentation would have been helpful. When restoring in a new namespace, you need to make sure multiple secrets are in the new namespace:
* the secret for `{dbName}-auth` that has the db credentials. If this isn't present, the validating webhook won't let you create a MySQL resource.
* the secret for `osm-{dbName}` (maybe `osm-{snapshotName}`, mine were the same). Info on credentials for osm to get/put the snapshot. If this isn't present, the MySQL with snapshotSource will fail to load because it tries to use this secret as a volume.

**Comment by vipulagarwal** [comment]
> This is not currently possible, since we don't allow selecting Snapshot from a different namespace. To work around, you can manually copy the Snapshot object and it's associated secret to the desired namespace and then use that Snapshot.

@tamalsaha can you elaborate on how to copy a snapshot object to other namespace? When I try to create it through the yaml dump, the admission webhook gives the following error:
`Error from server (Forbidden): error when creating "snap.yaml": admission webhook "snapshot.validators.kubedb.com" denied the request: elasticsearches.kubedb.com "elasticsearch-test" not found`

`elasticsearch-test` instance exists in the original namespace but not in the new namespace. I am sure there must be another way to do this but I am not able to find anything in the documentation.

**Comment by savealive** [comment]
Cross-namespace snapshot would be a very useful feature. We have dynamic review environments which need to be restored from "golden image" snapshot in staging.

**Comment by savealive** [comment]
And regarding the workaround.  Considering we have a snapshot *kubedb-mysql-20190929-225507* in *staging* ns and we're about to deploy a new DB from snapshot in *mysql-test* ns.
In order to get it working we need the following objects in *mysql-test*
* osm secret (generated by controller on restore from snapshot and simply copied to destination ns)
it's base64 encoded text:
```
contexts:
- config:
    access_key_id: <your key id>
    auth_type: accesskey
    region: eu-west-1
    secret_key: <your secret key>
  name: objectstore
  provider: s3
```
* root user/password secret matching one in staging (mysql-auth)
* PVC with size matching size requested in snapshot

*init.snapshotSource.namespace* must be "staging" (source namespace) in order to let restore job find proper file on S3.
working example:
```
apiVersion: v1
data:
  config: <encoded data>
kind: Secret
metadata:
  name: osm-mysql-20190929-225507
type: Opaque
---
apiVersion: v1
data:
  password: WkZNX2ZDDVS5J95hX0F1ZQ==
  username: cm9vdA==
kind: Secret
metadata:
  name: mysql-root
---
apiVersion: v1
data:
  mysql.cnf: |-
    [mysqld]
    skip-host-cache
    skip-name-resolve
    log_bin_trust_function_creators
    sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    max_connections = 200
    read_buffer_size = 1048576
kind: ConfigMap
metadata:
  name: mysql-configuration
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: ebs-sc
  name: kubedb-mysql-20190929-225507
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ebs-sc
  volumeMode: Filesystem
---
apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysql
spec:
  version: "8.0-v2"
  configSource:
    configMap:
      name: mysql-configuration
  storageType: Ephemeral
  databaseSecret:
    secretName: mysql-root
  storage:
    storageClassName: "ebs-sc"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  terminationPolicy: wipeOut
  podTemplate:
    spec:
      resources:
        requests:
          memory: "256m"
          cpu: "50m"
  init:
    snapshotSource:
      name: mysql-20190929-225507
      namespace: staging
```
