### ISSUE TITLE
Helm chart incorrectly assigns annotations to the deployment not the pod template

### ISSUE THREAD

**Issue by stormmore** [kubedb/project#392]
Either `annotations` in the values.yaml file should map to `spec.template.metadata.annotations` or there should be a separate value for pod and deployment annotations. For instance, for kube2iam and kiam, the annotation (iam.amazonaws.com/role) needs to be on the pod template metadata:

```
spec:
  template:
    metadata: 
      annotations:
        iam.amazonaws.com/role: S3Access
```
