### ISSUE TITLE
Missing privileges for ES snapshot

### ISSUE THREAD

**Issue by maartenvandenbogaard** [kubedb/project#394]
Apparently permissions set via Security Guard are too restrictive to run a successful snapshot.

Excerpt from the ES client logs:

```
client-maarten-0 elasticsearch [2019-01-10T10:03:26,183][INFO ][c.f.s.c.PrivilegesEvaluator] No cluster-level perm match for User [name=readall, roles=[], requestedTenant=null] Resolved [aliases=[], indices=[], allIndices=[], types=[*], isAll()=false, isEmpty()=false] [Action [cluster:monitor/main]] [RolesChecked [sg_readall]]
client-maarten-0 elasticsearch [2019-01-10T10:03:26,183][INFO ][c.f.s.c.PrivilegesEvaluator] No permissions for [cluster:monitor/main]

client-maarten-0 elasticsearch [2019-01-10T10:03:26,193][INFO ][c.f.s.c.PrivilegesEvaluator] No index-level perm match for User [name=readall, roles=[], requestedTenant=null] Resolved [aliases=[], indices=[test], allIndices=[test], types=[*], isAll()=false, isEmpty()=false] [Action [indices:monitor/settings/get]] [RolesChecked [sg_readall]]
client-maarten-0 elasticsearch [2019-01-10T10:03:26,193][INFO ][c.f.s.c.PrivilegesEvaluator] No permissions for [indices:monitor/settings/get]

client-maarten-0 elasticsearch [2019-01-10T10:03:26,655][INFO ][c.f.s.c.PrivilegesEvaluator] No cluster-level perm match for User [name=readall, roles=[], requestedTenant=null] Resolved [aliases=[], indices=[], allIndices=[], types=[*], isAll()=false, isEmpty()=false] [Action [cluster:monitor/main]] [RolesChecked [sg_readall]]
client-maarten-0 elasticsearch [2019-01-10T10:03:27,262][INFO ][c.f.s.c.PrivilegesEvaluator] No permissions for [indices:admin/mappings/get]
```

My snapshot configuration, basically following the how-to from https://kubedb.com/docs/0.9.0/guides/elasticsearch/snapshot/instant_backup/ here:
```
---
apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: maarten-snapshot
  namespace: estestje
  labels:
    kubedb.com/kind: Elasticsearch
spec:
  databaseName: maarten
  storageSecretName: gcs-secret
  gcs:
    bucket: mybucket
```

My ES configuration:
```
---
apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: maarten
  namespace: estestje
spec:
  version: "6.3-v1"
  topology:
    master:
      replicas: 1
      prefix: master
      storage:
        storageClassName: "standard"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    data:
      replicas: 2
      prefix: data
      storage:
        storageClassName: "standard"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    client:
      replicas: 1
      prefix: client
      storage:
        storageClassName: "standard"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
```
