### ISSUE TITLE
Cannot create postgres with wal s3 archiving due to invalid header 

### ISSUE THREAD

**Issue by creatorrr** [kubedb/project#408]
`kubectl create -f postgres.yaml` fails with the following error:

### Error

```
Error from server (Forbidden): error when creating "resources/production/postgres.yaml": admission webhook "postgres.validators.kubedb.com" denied the request: RequestError: send request failed
caused by: Get https://s3.amazonaws.com/electriqpower-database-backups?location=: net/http: invalid header field value "AWS4-HMAC-SHA256 Credential=AKIXXXXXXXXXXXXXX\n/20190131/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=b9a8b9cXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" for key Authorization
```

### Contents of postgres.yaml:
```yaml
---
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres-production-0
  namespace: production
spec:
  version: custom
  replicas: 3

  standbyMode: Hot
  storageType: Durable
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 36Gi

  archiver:
    storage:
      storageSecretName: s3-backup-user
      s3:
         bucket: xyz-database-backups
         prefix: production-01
```
