### ISSUE TITLE
Improve error handling in creating Instant Snapshots

### ISSUE THREAD

**Issue by dennisameling** [kubedb/project#410]
I was creating an Instant Snapshot with the following YAML:

```YAML
apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: snap-manual-20190202-173800
  namespace: ns1
  labels:
    kubedb.com/kind: MySQL
spec:
  databaseName: database
  storageSecretName: azure-secret
  azure:
    bucket: snapshots
```

This resulted in the following output:

```YAML
....
status:
  completionTime: "2019-02-02T16:13:24Z"
  phase: Failed
  reason: not found
  startTime: "2019-02-02T16:13:24Z"
```
The `reason` is quite limited here. What's not found exactly?

Turned out I made a typo in the Azure spec:

```YAML
...
  azure:
    bucket: snapshots
```
had to be
```YAML
...
  azure:
    container: snapshots
```
Please consider improving the error reason in this case, e.g. to something like `invalid configuration for azure storage provider`.
