### ISSUE TITLE
Postgres replica service does not use defined serviceTemplate

### ISSUE THREAD

**Issue by JustinHead** [kubedb/project#425]
If you set a serviceTemplate within your Postgres definition only the primary service adheres to the definition. The replica service does not use the definition at all.

```yaml
apiVersion: kubedb.com/v1alpha1
kind: Postgres
...
  serviceTemplate:
    metadata:
      annotations:
        name: postgres-internal-lb
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "180"
        service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    spec:
      type: LoadBalancer
      ports:
      - name: postgres
        port: 5432
```
