### ISSUE TITLE
Allow MongoDB to run without authentication

### ISSUE THREAD

**Issue by rassie** [kubedb/project#432]
There should be an option to run a MongoDB instance without authentication (I-know-what-I-am-doing kind of opt-in) to accomodate existing workflows e.g. in testing environments. The simplest way to do it would be to replace `--auth` with `--transitionToAuth` in the `StatefulSet` definition when some parameter is set on the CRD.

**Comment by rassie** [comment]
I have been able to workaround like this:
```
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: test-mongodb
spec:
  version: "3.6-v1"
  replicas: 3
  replicaSet:
    name: test
  podTemplate:
    spec:
      args:
      - --transitionToAuth
  storage:
[...]
```
It results in both `--auth` and `--transitionToAuth` being on the command line, which doesn't seem to bother `mongod`, while it accepts the latest argument, which is `--transitionToAuth`, as intended.

Feel free to close the ticket since we now have a workaround. An actual implementation might make sense, but that's not for me to decide.
