### ISSUE TITLE
deploy elasticsearch pods with different JVM setting

### ISSUE THREAD

**Issue by HarishHothi** [kubedb/project#443]
Hi,
    Currently we can configure elastic search topology to have different resource requirements. But JVM setting is common.
 ```
 master:
      replicas: 1
      prefix: master
      storage:
        storageClassName: "cinder-class"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      resources:
        requests:
          memory: "4096Mi"
          cpu: "2"
        limits:
          memory: "4096Mi"
          cpu: "2"
    data:
      prefix: data
      replicas: 4
      storage:
        storageClassName: "cinder-class"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 70Gi
      resources:
        requests:
          memory: "6144Mi"
          cpu: "2"
        limits:
          memory: "6144Mi"
          cpu: "2"
    client:
      prefix: client
      replicas: 2
      storage:
        storageClassName: "cinder-class"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
      resources:
        requests:
          memory: "4096Mi"
          cpu: "2"
        limits:
          memory: "4096Mi"
          cpu: "2"
```
But we have common JVM option
```
 podTemplate:
    spec:
      env:
      - name: ES_JAVA_OPTS
        value: "-Xms3072m -Xmx3072m"

```
Ideally Master pod does not require more memory. 
Can we have some way to specify this at each pod level?
`i.e master pod will have 2GB Memory and out of 2GB 1GB is for JVM, similary Data pod will have 8GB Memory and out of 8GB 4GB is for JVM.
`
