### ISSUE TITLE
Backing up Durable database with Ephemeral snapshotter in BackupScheduler

### ISSUE THREAD

**Issue by frelon** [kubedb/project#452]
Hi!

I'm trying to backup a Durable database to swift. I'm using the following resource-definition:

```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: quick-postgres-very-long-name-to-test-gluster
  namespace: stage
spec:
  version: "10.6"
  storageType: Durable
  storage:
    storageClassName: "glusterfs"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: Delete
  backupSchedule:
    cronExpression: "@every 1m"
    storageSecretName: swift-secret
    swift:
      container: utv-backups
      prefix: test
```

But when the snapshotter is running it cannot create a PVC because of the following error: "failed to create volume: failed to create endpoint/service stage/glusterfs-dynamic-kubedb-quick-postgres-very-long-name-to-test-20190308-153121: error creating service: Service "glusterfs-dynamic-kubedb-quick-postgres-very-long-name-to-test-20190308-153121" is invalid: metadata.name: Invalid value: "glusterfs-dynamic-kubedb-quick-postgres-very-long-name-to-test-20190308-153121": must be no more than 63 characters".

I would like to solve this by using an emptyDir volume when running the snapshotter instead... Is that possible? (Setting StorageType=Ephemeral of snapshot generated by BackupSchedule)
