### ISSUE TITLE
deleting a Postgres database also deletes pre-existing secret

### ISSUE THREAD

**Issue by bodewig** [kubedb/project#453]
I'm setting up an admin secret manually before installing the Postgres resource. When I delete Postgres the secret is deleted as well, even though it is not supposed to be owned by kubedb.

First create a secret via (everything happens in namespace database)

```
apiVersion: v1
kind: Secret
metadata:
  name: foodb-auth
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: really_secret
```

the create the Postgres object

```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: foodb
spec:
  version: "10.2-v2"
  databaseSecret:
    secretName: foodb-auth
  replicas: 2
  standbyMode: Hot
  streamingMode: asynchronous
  leaderElection:
    leaseDurationSeconds: 3
    renewDeadlineSeconds: 2
    retryPeriodSeconds: 1
  storageType: "Durable"
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  updateStrategy:
    type: RollingUpdate
  terminationPolicy: WipeOut
```

wait for the DB to be provisiioned and then remove the object again

```
kubectl delete pg foodb -n database
```

wait for kubedb to perform its magic. After that `kubectl get secret foodb-auth -n database` results in `secrets "foodb-auth" not found`.

I initially thought this would be triggered by the secret having the same name kubedb would create by itself. But if I use `foodb-secret` rather than `foodb-auth` then the secret still is deleted together with the database.
