### ISSUE TITLE
Snapshot is always failing

### ISSUE THREAD

**Issue by schmitch** [kubedb/project#464]
Currently my snapshot always fails with:
```
Events:
  Type     Reason          Age   From             Message
  ----     ------          ----  ----             -------
  Warning  SnapshotFailed  15s   KubeDB operator  not found
```

The Snapshot is the following:
```
apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: instant-snapshot
  namespace: postgres
  labels:
    kubedb.com/kind: Postgres
spec:
  databaseName: envisia
  storageSecretName: gcloud-secret
  gcs:
    bucket: envisia-postgres-backups
```

(Currently automatic Snapshots via https://kubedb.com/docs/0.10.0/guides/postgres/snapshot/scheduled_backup/ also have the same error)

I am using the same secret for the `archiver`which actually works correctly.

Snapshot, Database and Secret is in the same namespace, the operator is not.

Postgres Version: 1.11
Kubernetes Version: 1.12 (GKE 1.12.5-gke.5)
