### ISSUE TITLE
Incorrect podTemplate example in concepts/databases/postgres.md

### ISSUE THREAD

**Issue by harbesc** [kubedb/project#466]
```
  podTemplate:
    annotation:
      passMe: ToDatabasePod
```
Should be...

```
  podTemplate:
    metadata:
      annotations:
        passMe: ToDatabasePod
```
I was able to add my necessary annotations for datadog after using the latter.
