### ISSUE TITLE
AKS admission webhook "mongodb.validators.kubedb.com" denied the request: invalid ResourceStorage request

### ISSUE THREAD

**Issue by polganesh** [kubedb/project#473]
I am trying to use kubedb for my azure kubernetes cluster (AKS)
**system details**
Cloud provider :-  Azure
K8s version :- 1.12.5
Kubedb version:- 0.11.0

**steps  taken to configure kubedb**
follow steps available at [https://kubedb.com/docs/0.11.0/setup/install/](url)
_installed kubedb-operator and kubedb-catalog_
helm install appscode/kubedb --name kubedb-operator --version 0.11.0 --namespace kube-system --set enableAnalytics=false --set rbac.create=true

helm install appscode/kubedb-catalog --name kubedb-catalog --version 0.11.0 --namespace kube-system --set enableAnalytics=false --set rbac.create=true

trying to install mongodb as a chart

```
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: skeleton-mongodb
spec:
  version: 4.1.7
  replicas: {{ .Values.mongoDbReplicaCount }}
  replicaSet:
    name: rs0
  storage:
    storageClassName: default
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.mongoDbStorageCapacity }}
```

values.yaml
```
replica-count: 1
acr: myacr
tag: my-tag
env: test
domain: example.com
mongoDbReplicaCount: 2
mongoDbStorageClass: "default"
mongo-db-storage-capacity: 10Gi

```

when executing helm for this got following error

> Error: release skeleton failed: admission webhook "mongodb.validators.kubedb.com" denied the request: invalid ResourceStorage request

**Comment by tamalsaha** [comment]
Note the error message: `storageClassName: default`. Sounds like you don't have a Storageclass called default.

Try `kubectl get storageclasses` and use a valid name.

**Comment by polganesh** [comment]
result of about command is 

![image](https://user-images.githubusercontent.com/13764801/55052145-1fa8a180-5058-11e9-9a38-1244befe070a.png)

i tried running mongodb kubedb object on different cluster it works fine with kubectl
when i try to integrate in existing helm chart it gives me problem. i tried providing explicit value for storageClassName as well instead of  but it does not work

**Comment by tamalsaha** [comment]
Can you share the log of kubedb operator? Also, what version of kubedb operator are you using?

**Comment by tamalsaha** [comment]
Actually I found the error:
https://github.com/kubedb/apimachinery/blob/master/pkg/validator/validate.go#L36

You need to specify storage amount you want.
```
    resources:
      requests:
        storage: 1Gi
```

**Comment by hossainemruz** [comment]
@polganesh You don't have `mongoDbStorageCapacity` entry in your `values.yaml` file. Instead, you have `mongo-db-storage-capacity: 10Gi`.

Either use `storage: {{ .Values.mongo-db-storage-capacity }}` in MongoDB crd or rename `mongo-db-storage-capacity` to `mongoDbStorageCapacity` in your `values.yaml` file.

**Comment by polganesh** [comment]
Hi ,
I tried all the possibilities.
following are the latest.

```
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: skeleton-mongodb
spec:
  version: 4.1.7
  replicas: {{ .Values.mongoDbReplicaCount }}
  replicaSet:
    name: rs0
  storage:
    storageClassName: {{ .Values.mongoDbStorageClass }}
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.mongoDbStorageCapacity }}

```

```
mongoDbReplicaCount: 2
mongoDbStorageClass: "default"
mongoDbStorageCapacity: 10Gi

```

**logs from operator**
I0327 06:14:50.436407       1 xray.go:232] testing ValidatingWebhook using an object with GVR = kubedb.com/v1alpha1, Resource=redises 

I0327 06:14:59.741147       1 apiservice.go:58] Patching APIService v1alpha1.validators.kubedb.com with {"metadata":{"annotations":{"admission-webhook.appscode.com/active":"true","admission-webhook.appscode.com/status":""}}}. 

still, I am getting the same error

helm upgrade skeleton helm-charts/skeleton --install

![image](https://user-images.githubusercontent.com/13764801/55056105-82ed0080-5065-11e9-94ce-54d9db6f73ff.png)

**Comment by tamalsaha** [comment]
Can you show us the command you used to install the chart?

**Comment by polganesh** [comment]
In order to install chart which contains mongodb I used following command . This command is for upgrade . Even if I try to use install command I am getting similar error

helm upgrade skeleton helm-charts/skeleton --install

**Comment by polganesh** [comment]
one more observation

when i am executing simple kubectl apply things work well.

consider following k8s file **mongo-replica-sets.yaml**

```
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mgo-replicaset
 # namespace: demo
spec:
  version: 4.1.7
  replicas: 5
  replicaSet:
    name: rs0
  storage:
    storageClassName: "default"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
```
![image](https://user-images.githubusercontent.com/13764801/55067285-bb013d00-507f-11e9-9643-784f53d892c7.png)

![image](https://user-images.githubusercontent.com/13764801/55067406-f0a62600-507f-11e9-8468-3755b785e8f4.png)

i am new to k8s operators i am not sure what is implication of providing -**-enable-validating-webhook=false** as far as we are providing correct values
