### ISSUE TITLE
Support Local volume for PostgreSQL WAL archiving

### ISSUE THREAD

**Issue by david-ecc** [kubedb/project#475]
WAL-archiving to [PVC seems to be supported in the CRD](https://github.com/kubedb/apimachinery/blob/release-0.11/api/crds/postgres.yaml#L911), but i always get this error message:

`admission webhook "postgres.validators.kubedb.com" denied the request: no storage provider is configured`

This is my configuration:

```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: testpg
spec:
  version: "11.1-v1"
  storageType: Durable
  storage:
    storageClassName: "thin"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  terminationPolicy: Delete
  archiver:
    storage:
      local:
        persistentVolumeClaim:
          claimName: pgbackup-cifs
```

I'm using version  0.11.0

**Comment by tamalsaha** [comment]
Wal-g archiving is not supported for Local PVC. Current you can use s3, gcs, azure or swift storage. Please see here: https://kubedb.com/docs/0.11.0/guides/postgres/snapshot/continuous_archiving/

**Comment by david-ecc** [comment]
Is there a reason why this is not supported in kubedb? Wal-g supports writing local files.

**Comment by tamalsaha** [comment]
We can add support for it. No one has asked for it so far.

**Comment by tamalsaha** [comment]
```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: testpg
spec:
  version: "11.1-v1"
  storageType: Durable
  storage:
    storageClassName: "thin"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  terminationPolicy: Delete
  archiver:
    storage:
      local:
        persistentVolumeClaim:
          claimName: pgbackup-cifs
        mountPath: /data/pgbackup-cifs
```

- https://github.com/kubedb/postgres/blob/master/pkg/controller/statefulset.go#L218

- 
```
  elif [[ ${ARCHIVE_FILE_PREFIX} != "" ]]; then
    export WALG_FILE_PREFIX="${ARCHIVE_FILE_PREFIX}/$(hostname)"
    mkdir =p $WALG_FILE_PREFIX
```
