### ISSUE TITLE
mongodb with custom root user is not making mongodb pod up

### ISSUE THREAD

**Issue by polganesh** [kubedb/project#477]
following is my skeleton-mongodb,yaml file present in helm chart
it is configured to load credentials from secret named as a **skeleton**
```
---
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: skeleton-mongodb
spec:
  version: 4.1.7
  databaseSecret:
    secretName: skeleton
  replicas: {{ .Values.mongoDbReplicaCount }}
  replicaSet:
    name: rs0
  storage:
    # storageClassName: {{ .Values.mongoDbStorageClass }}
    storageClassName: {{ index .Values "mongoDbStorageClass"}}
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.mongoDbStorageCapacity }}
```
my secret

```
apiVersion: v1
data: 
  password: <64 bit encoded value>
  username: <64 bit encoded value>
kind: Secret
metadata: 
  name: skeleton
type: Opaque

```
i am unable to see my pod for mongodb up even after 1 hour

![image](https://user-images.githubusercontent.com/13764801/55108749-8075bf80-50d4-11e9-955e-2996242a63c1.png)

also i am not sure about
how to provide  and create non root user credentials. 
is it possible to provide own key names instead of ( default username,password) e.g.

```
apiVersion: v1
data: 
  root-password: <64 bit encoded value>
  root-username: <64 bit encoded value>
  nonroot-password: <64 bit encoded value>
  nonroot-username: <64 bit encoded value>
kind: Secret
metadata: 
  name: skeleton
type: Opaque

```
