### ISSUE TITLE
mongodb annotations not working for created service

### ISSUE THREAD

**Issue by polganesh** [kubedb/project#484]
Hi,
As per documentation available at [URL](https://kubedb.com/docs/0.11.0/guides/mongodb/) when we create mongodb object it will create pv,service, stateful set.

in order to provide annotations to service we use following 

> serviceTemplate:
>     annotations:
>         service.beta.kubernetes.io/azure-load-balancer-internal: "true"
>         external-dns.alpha.kubernetes.io/hostname: "skeleton-mongodb.private.{{ .Values.env }}.{{ .Values.domain }}"

complete mongodb yaml file is 

```
---
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: skeleton-mongodb
spec:
  serviceTemplate:
    annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        external-dns.alpha.kubernetes.io/hostname: "skeleton-mongodb.private.{{ .Values.env }}.{{ .Values.domain }}"
  version: {{ .Values.mongoDbVersion }}
  databaseSecret:
    secretName: skeleton
  replicas: {{ .Values.mongoDbReplicaCount }}
  replicaSet:
    name: rs0
  storage:
    # storageClassName: {{ .Values.mongoDbStorageClass }}
    storageClassName: {{ index .Values "mongoDbStorageClass"}}
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.mongoDbStorageCapacity }}
```
values for it

```
env: int
 domain: example.com
 mongoDbReplicaCount: 2
 mongoDbStorageClass: managed-premium
 mongoDbStorageCapacity: 10Gi
 mongoDbVersion: 4.1.7
```

when i check annotations of service created by mongodb. i am unable to find annotation for it.

![image](https://user-images.githubusercontent.com/13764801/55404892-36b82980-5559-11e9-83b8-5cfaa6c75f39.png)

earlier when we are creating service explicitly it shows following 

![image](https://user-images.githubusercontent.com/13764801/55405345-1fc60700-555a-11e9-8b45-14741c9c2006.png)

**Comment by polganesh** [comment]
@tamalsaha can you please help into this

**Comment by the-redback** [comment]
The actual format is 

```
spec:
  serviceTemplate:
    metadata:
      annotations:
```

It's working on `0.12.0`. @polganesh can you verify if it's working?
