### ISSUE TITLE
[elasticsearch] Is creating unwanted kubedb service

### ISSUE THREAD

**Issue by botzill** [kubedb/project#489]
I have the following cluster config for ES:

```
{{- $fullName := include "elasticsearch.fullname" . -}}
apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "elasticsearch.name" . }}
    helm.sh/chart: {{ include "elasticsearch.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  version: "{{ .Values.version }}"
  replicas: {{ .Values.cluster.replicas }}
  authPlugin: "SearchGuard"
  enableSSL: {{ .Values.enableSSL }}
  env:
    - name: ES_JAVA_OPTS
      value: "-Xms1g -Xms1g"
{{- if .Values.databaseSecret }}
  databaseSecret:
    secretName: {{ $fullName }}-auth
{{- end }}
  storageType: "Durable"
  storage:
    storageClassName: "{{ .Values.storage.storageClass }}"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "{{ .Values.storage.size }}"
  monitor:
    agent: prometheus.io/builtin
    prometheus:
      labels:
        app.kubernetes.io/name: {{ include "elasticsearch.name" . }}
      interval: 10s
  configSource:
    configMap:
      name: {{ $fullName }}-config
  podTemplate:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    controller:
      annotations:
      {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    spec:
      resources:
{{ toYaml .Values.resources | indent 8 }}
  serviceTemplate:
    annotations:
      passMe: ToService
    spec:
      type: ClusterIP
      ports:
      - name:  http
        port:  9200
        targetPort: http
  updateStrategy:
    type: "RollingUpdate"
  terminationPolicy: "{{ .Values.terminationPolicy }}"
```

and it is creating a service called `kubedb`
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-04-05T21:52:19Z"
  name: kubedb
  namespace: elk
  resourceVersion: "60864"
  selfLink: /api/v1/namespaces/elk/services/kubedb
  uid: 157ef4a5-57ed-11e9-8078-8a46af73b7ab
spec:
  clusterIP: None
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

is this an issue or it's used for smth?
