### ISSUE TITLE
Postgres WAL-archiving to Minio broken

### ISSUE THREAD

**Issue by david-ecc** [kubedb/project#492]
Saving basebackup/wal to Minio does not work, because these environment-variables for wal-g are missing: 

```
AWS_ENDPOINT: http://LOCALIP:9000
AWS_S3_FORCE_PATH_STYLE: true
```
Adding them manually to the StatefulSet works fine. 

My config:
```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: meinpg3
spec:
  version: "11.1-v1"
  storageType: Durable
  storage:
    storageClassName: "thin"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  terminationPolicy: Delete
  archiver:
    storage:
      storageSecretName: minio-secret
      s3:
        bucket: pgbackup
        endpoint: http://LOCALIP:9000
```

Error without setting environment:
```
FATAL: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
	status code: 403, request id: REMOVED, host id: REMOVED
AWS_REGION is not set and s3:GetBucketLocation failed
github.com/wal-g/wal-g/internal/storages/s3.getAWSRegion
	/go/src/github.com/wal-g/wal-g/internal/storages/s3/session.go:47
github.com/wal-g/wal-g/internal/storages/s3.createSession
	/go/src/github.com/wal-g/wal-g/internal/storages/s3/session.go:76
github.com/wal-g/wal-g/internal/storages/s3.ConfigureFolder
	/go/src/github.com/wal-g/wal-g/internal/storages/s3/folder.go:74
github.com/wal-g/wal-g/internal.configureFolder
	/go/src/github.com/wal-g/wal-g/internal/configure.go:51
github.com/wal-g/wal-g/internal.Configure
	/go/src/github.com/wal-g/wal-g/internal/configure.go:132
main.main
	/go/src/github.com/wal-g/wal-g/cmd/wal-g/main.go:132
runtime.main
	/usr/local/go/src/runtime/proc.go:201
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1333
failed to create new session
```
