### ISSUE TITLE
[elasticsearch] Support for version 7.x

### ISSUE THREAD

**Issue by botzill** [kubedb/project#496]
Hi.

Currently, ElasticSearch 7.0.0 is officially released. Do you have any plans to support it as well? 

Thx.

**Comment by jalberto** [comment]
@botzill you can create your own version (will be simpler if #436 is implemented thou)

```
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  clusterName: ""
  labels:
    app: kubedb-catalog
    chart: kubedb-catalog-0.11.0
    heritage: Tiller
    release: kubedb-catalog
  name: "7.0-official"
spec:
  db:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.0
  exporter:
    image: kubedb/elasticsearch_exporter:1.0.2
  initContainer:
    image: kubedb/busybox
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
    snapshotterPolicyName: elasticsearch-snapshot
  tools:
    image: kubedb/elasticsearch-tools:6.5.3
  version: 7.0.0
```
