### ISSUE TITLE
Elasticsearch monitors only scrapes client node

### ISSUE THREAD

**Issue by heron182** [kubedb/project#500]
So after enable monitoring of Elasticsearch using this guide: https://kubedb.com/docs/0.11.0/guides/elasticsearch/monitoring/using-coreos-prometheus-operator/ 
I noticed that the service only created one endpoint (for the client node). 

The data nodes match the Service selector but they don't have a sidecar exporter container nor the scrapping port is configured. Is that the expected behavior ?

elastic stats service:

```
  ports:
  - name: prom-http
    port: 56790
    protocol: TCP
    targetPort: prom-http
  selector:
    kubedb.com/kind: Elasticsearch
    kubedb.com/name: elasticsearch-logging
```

elastic client node:
```
    image: kubedb/elasticsearch_exporter:1.0.2
    imagePullPolicy: IfNotPresent
    name: exporter
    ports:
    - containerPort: 56790
      name: prom-http
      protocol: TCP
```

elastic node exporter:
```
Does not have a exporter img nor prom-http port configured
```

Full elastic spec:
```
apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch-logging
spec:
  podTemplate:
    spec:
      env:
        - name: ES_JAVA_OPTS
          value: -Xms2000m -Xmx2000m
        
  version: 6.5.3
  authPlugin: None
  topology:
    master:
      prefix: master
      replicas: 1
      storage:
        storageClassName: standard
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
          
    data:
      prefix: data
      replicas: 2
      storage:
        storageClassName: standard
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
          
    client:
      prefix: client
      replicas: 1
      storage:
        storageClassName: standard
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
          
  nodeSelector:
    elk_node: "True"
    
  tolerations:
    - effect: NoSchedule
      key: node.dev/elk_node
      operator: Exists
    
  doNotPause: false
  serviceTemplate:
    spec:
      type: NodePort
      ports:
      - name:  http
        port:  9200
        nodePort: 30200
        targetPort: http
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      interval: 10s
      labels:
        release: prometheus-operator
      namespace: monitoring
```
