### ISSUE TITLE
Unable to authenticate the request due to an error: [x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "front-proxy-ca"), x509: certificate signed by unknown authority]

### ISSUE THREAD

**Issue by dano0b** [kubedb/project#513]
Clean kubernetes 1.13.4 setup, other operators work normally like rook/ceph.

Tried with default `apiserver.ca` and with the real one retrieved via `kubectl config view --minify=true --flatten -o jsonpath='{.clusters[0].cluster.certificate-authority-data}'` (base64 decoded for re-encoding...).

kubedb version: 0.11.0

install via ansible:
```
- name: install kubedb operator helm chart
  helm:
    host: localhost
    chart:
      name: kubedb
      version: 0.11.0
      source:
        type: repo
        location: https://charts.appscode.com/stable
    values:
      enableAnalytics: false
      apiserver.ca: "{{ ca.stdout | b64decode }}"
    state: present
    name: kubedb-operator
    namespace: kubedb
  environment:
    KUBECONFIG: "{{ playbook_dir }}/kubeconfig"
    TILLER_NAMESPACE: kube-system
- name: wait for kubedb crds
  pause:
    seconds: 5
- name: install kubedb catalog helm chart
  helm:
    host: localhost
    chart:
      name: kubedb-catalog
      version: 0.11.0
      source:
        type: repo
        location: https://charts.appscode.com/stable
    values:
      enableAnalytics: false
    state: present
    name: kubedb-catalog
    namespace: kubedb
  environment:
    KUBECONFIG: "{{ playbook_dir }}/kubeconfig"
    TILLER_NAMESPACE: kube-system
```

error message / log spammed:
```
I0430 07:09:55.791833       1 xray.go:232] testing ValidatingWebhook using an object with GVR = kubedb.com/v1alpha1, Resource=redises
E0430 07:09:55.794304       1 authentication.go:65] Unable to authenticate the request due to an error: [x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "front-proxy-ca"), x509: certificate signed by unknown authority]
```

no creation of a postgres cluster is possible.

Didn't receive help in the slack channel so I guess it is a bug and not a configuration issue.
