### ISSUE TITLE
[elasticsearch] Sample config for monitoring in doc fails!

### ISSUE THREAD

**Issue by occelebi** [kubedb/project#524]
I tried to monitor ES with prometheus-operator with sample config written in doc:

```
spec:
  ...
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      namespace: monitoring
      labels:
        k8s-app: prometheus
      interval: 10s
```

Results in:
`invalid 'Monitor.Prometheus' in '{"agent":"prometheus.io/coreos-operator","prometheus":{"namespace":"monitoring","labels":{"k8s-app":"prometheus"},"interval":"10s"},"resources":{}}'. Prometheus.Port value must be between 1024 and 65535, inclusive`

It seems it is hitting [here](https://github.com/kubedb/apimachinery/blob/5ba915343400bf22c60b013eea798bfea21e4f8f/pkg/validator/validate.go#L103). Any idea ?

**Comment by occelebi** [comment]
I found that on [doc](https://kubedb.com/docs/0.9.0/guides/elasticsearch/monitoring/using-coreos-prometheus-operator/) (version 0.9.0): 
`prometheus.port indicates the port for Elasticsearch exporter endpoint (default is 56790)`
However appearently default port is not 56970 in current version of kubedb. Doc/Kubedb update is needed! @tamalsaha 
```
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      namespace: demo
      labels:
        k8s-app: prometheus
      interval: 10s
      port: 56790
```
