### ISSUE TITLE
[Question] How to use Redis Cluster in NodeJS

### ISSUE THREAD

**Issue by ToonvanStrijp** [kubedb/project#535]
I'm trying to use a redis cluster inside my nodejs application. Right now I use TypeORM for the database this package has an option for redis caching [https://github.com/typeorm/typeorm/blob/master/docs/caching.md](https://github.com/typeorm/typeorm/blob/master/docs/caching.md) 
I'm not sure how the config should look like, and would like to know if someone can help me with this.

Cause I see a lot of multiple nodes inside the explanation of TypeORM but kubernetes is only exposing one service with port 6379.

My current redis yaml for kubedb looks like this:
```
apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis-cluster-ticketapp-api
  namespace: ticketapp
spec:
  version: 5.0.3-v1
  mode: Cluster
  cluster:
    master: 3
    replicas: 1
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 3Gi
    storageClassName: "do-block-storage"
    accessModes:
      - ReadWriteOnce
  updateStrategy:
    type: RollingUpdate
```
