### ISSUE TITLE
Cannot delete Redis database

### ISSUE THREAD

**Issue by alec-benson** [kubedb/project#539]
Hi,
I have a redis database that I am trying to delete. This is the YAML for the resource:

```
apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis-cluster
  namespace: default
spec:
  version: "5.0.3-v1"
  configSource:
    configMap:
      name: redis-cluster-config
  mode: Cluster
  cluster:
    master: 3
    replicas: 1
  storageType: Durable
  podTemplate:
    spec:
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "12Gi"
          cpu: "1"
      affinity:
        podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                matchLabels:
                    kubedb.com/kind: Redis
                    kubedb.com/name: redis-cluster
  storage:
    storageClassName: standard
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      namespace: monitoring
      labels:
        release: prometheus-operator
      interval: 10s
```

I have noticed that if I try to delete the redis database before it becomes healthy, it never gets deleted. This is a problem if my database gets stuck in an unhealthy state, because I can't re-create the database until the old one is gone.

I think this issue is related to https://github.com/kubedb/project/issues/494
However, I haven't found any workaround. No matter what, the database stays on the system.

Thanks.
