### ISSUE TITLE
MongoDB: support setting pod and statefulset labels

### ISSUE THREAD

**Issue by sfitts** [kubedb/project#544]
Based on both the documentation and some experimentation it seems that you cannot currently set the labels for either the stateful set or pods created by KubeDB.  Pod labeling is very important to us so this is a major pain point.

**Comment by the-redback** [comment]
statefulset labels can be set like this.
```
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mongo-sh
  namespace: demo
  labels:
    mongodb: mg
spec:
  version: 3.6-v4
  shardTopology:
    configServer:
      replicas: 3
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
    mongos:
      replicas: 2
      strategy:
        type: RollingUpdate
    shard:
      replicas: 3
      shards: 3
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
  updateStrategy:
    type: RollingUpdate
  storageType: Durable
  terminationPolicy: WipeOut
```

Here, label `mongodb: mg` is forwarded to statefulsets.
