### ISSUE TITLE
Postgres question about WAL archiving from replica

### ISSUE THREAD

**Issue by tpatrascu** [kubedb/project#547]
Hello,

I have a question regarding wal-g continuous archiving from the Postgres replica. 

According to the Postgres documentation at https://www.postgresql.org/docs/10/warm-standby.html#CONTINUOUS-ARCHIVING-IN-STANDBY, when sending archive logs from the replica ` the archive_command must test if the file being archived exists already`.

I have set the WAL-G env var in the podTemplate:

```
  podTemplate:
    spec:
      env:
      - name: WALG_PREVENT_WAL_OVERWRITE
        value: "1"
```

Should this be added by default?

Thanks!
