### ISSUE TITLE
[install/helm] Support configurable operator resources

### ISSUE THREAD

**Issue by kir4h** [kubedb/project#550]
As of v0.12.0, operator deployment doesn't allow configuring its requests and limits resources and instead a value for requests.limits.cpu is hardcoded:
```yaml 
resources:
  requests:
    cpu: "100m"
```
Those resources should be configurables to be able to adapt to different environments
