### ISSUE TITLE
Namespace can't be deleted when kubeDB is installed

### ISSUE THREAD

**Issue by cmoulliard** [kubedb/project#585]
### Versions
- KubeDB: 0.12.0
- Kubernetes Master: v1.11.0+d4cacc0
- OpenShift : v3.11.0+ea42280

### Description

The Namespace can't be deleted when kubeDB is installed on the ocp cluster

### Steps to reproduce

- Install KubeDB on openshift
```
#!/usr/bin/env bash

#
# Prerequisite : install tool jq
# This script assumes that KubeDB & Component operators are installed
#
# End to end scenario to be executed on minikube, minishift or k8s cluster
# Example: ./scripts/end-to-end.sh CLUSTER_IP
# where CLUSTER_IP represents the external IP address exposed top of the VM
#
CLUSTER_IP=${1:-192.168.99.50}
NS=${2:-test1}
SLEEP_TIME=10s

function deleteResources() {
  result=$(kubectl api-resources --verbs=list --namespaced -o name)
  for i in $result[@]
  do
    kubectl delete $i --ignore-not-found=true --all -n $1
  done
}

function listAllK8sResources() {
  result=$(kubectl api-resources --verbs=list --namespaced -o name)
  for i in $result[@]
  do
    kubectl get $i --ignore-not-found=true -n $1
  done
}

function printTitle {
  r=$(typeset i=${#1} c="=" s="" ; while ((i)) ; do ((i=i-1)) ; s="$s$c" ; done ; echo  "$s" ;)
  printf "$r\n$1\n$r\n"
}


printTitle "Creating the namespace"
kubectl create ns ${NS}

printTitle "Deploy a ServiceAccount"
cat <<EOF | kubectl apply -n ${NS} -f -
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test1
EOF
echo "Sleep ${SLEEP_TIME}"
sleep ${SLEEP_TIME}

#printTitle "List all resources"
#listAllK8sResources $NS

printTitle "Delete the serviceaccount"
kubectl delete components,links --all -n ${NS}
echo "Sleep ${SLEEP_TIME}"
sleep ${SLEEP_TIME}

printTitle "Delete pending resources using ApiServices registered"
deleteResources $NS

printTitle  "Delete namespace $NS"
kubectl delete ns $NS
```
- Execute the following bash script 

- Status of the namespace stays at `terminating`

The namespace can't be deleted as for an unknown resource kubedb added the finalizer string

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/sa.scc.mcs: s0:c15,c10
    openshift.io/sa.scc.supplemental-groups: 1000230000/10000
    openshift.io/sa.scc.uid-range: 1000230000/10000
  creationTimestamp: "2019-07-04T11:27:26Z"
  deletionTimestamp: "2019-07-04T11:27:55Z"
  name: test1
spec:
  finalizers:
  - kubernetes
```

and k8s is waiting that kubedb will remove the string `finalizer`

The problem is perhaps related to this message reported by the command `kubectl api-resources`

```
error: unable to retrieve the complete list of server APIs: 
mutators.kubedb.com/v1alpha1: the server is currently unable to handle the request,
validators.kubedb.com/v1alpha1: the server is currently 
```
