### ISSUE TITLE
Postgres restore from WAL stuck

### ISSUE THREAD

**Issue by kapolos** [kubedb/project#586]
I was testing the backup and restore via WAL/MinIO and it seems that it doesn't work.

First I created a test deployment and set it up to archive in a Minio Bucket. Then I created a table as per the documentation example.

test.yaml:
```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: pgtest
  namespace: infra
spec:
  version: "11.2"
  replicas: 3
  podTemplate:
    spec:
      nodeSelector:
        role: core
  standbyMode: Hot
  storageType: Durable
  storage:
    storageClassName: local-path
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  archiver:
    storage:
      storageSecretName: sc-bucket-cluster1-creds
      s3:
        endpoint: "https://minio.cl1.***"
        bucket: testpg
        prefix: pg
  terminationPolicy: WipeOut
  configSource:
   configMap:
     name: pgtest-conf
```

WAL archiving seems to work:
![image](https://user-images.githubusercontent.com/10794126/60764162-02d72d80-a08d-11e9-800b-95c4aa9dafba.png)

Then I created another deployment with init set to the archive.

**test-restore.yaml**:
```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: pgtest-restore
  namespace: infra
spec:
  version: "11.2"
  replicas: 3
  podTemplate:
    spec:
      nodeSelector:
        role: core
  standbyMode: Hot
  storageType: Durable
  storage:
    storageClassName: local-path
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  databaseSecret:
    secretName: "pgtest-auth"
  init:
    postgresWAL:
      storageSecretName: sc-bucket-cluster1-creds
      s3:
        endpoint: "https://minio.cl1.***"
        bucket: testpg
        prefix: "pg/kubedb/infra/pgtest/archive"
  archiver:
    storage:
      storageSecretName: sc-bucket-cluster1-creds
      s3:
        endpoint: "https://minio.cl1.***"
        bucket: testpg-restore
  terminationPolicy: WipeOut
  configSource:
   configMap:
     name: pgtest-conf
```

But the restore process gets stuck forever with `waiting for archived backup...`

![image](https://user-images.githubusercontent.com/10794126/60764178-68c3b500-a08d-11e9-8f24-8b7dff9cc716.png)

Am I doing something wrong or is it a bug?
