### ISSUE TITLE
Could not create postgresql service port other than "api" portname

### ISSUE THREAD

**Issue by kannanvj** [kubedb/project#589]
Hi All,
   I have tried creating the service for postgresql as per example provided in the below URL,
https://kubedb.com/docs/0.12.0/concepts/databases/postgres/#postgres-spec

But the service port is not created as mentioned on the URL.
If we have created the postgresql service port with the portname as "api", then it is working fine 
```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres-db-9
  namespace: demo
spec:
  version: "10.2-v4"
  storageType: Durable
  storage:
    storageClassName: "gluster"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  serviceTemplate:
    spec:
      ports:
      - name: api
        port: 3000
        targetPort: http
  terminationPolicy: WipeOut
```
User should know that portname must be  api. it is not mentioned on the document.
Or kubedb operator should accept the portname which provided by the CRD.
Its a bug either document or the code.
Kindly fix the same
