### ISSUE TITLE
Can not add extra arguments to elasticsearch exporter

### ISSUE THREAD

**Issue by HarishHothi** [kubedb/project#594]
While trying to setup, elastic search monitoring via Prometheus, Wanted to add es.all=true and es.indices=true argument to elasticsearch exporter sidecar. To do that I am using below elastic CRD snippets to configure elastic cluster with coreos prometheus operator.

```
init:
    scriptSource:
      configMap:
        name: es-init-script
  monitor:
    agent: prometheus.io/coreos-operator
    args:
    - --es.all=true
    - --es.indices=true
    prometheus:
      namespace: prometheus
      labels:
        app: kubedb
      interval: 10s
  configSource:
    configMap:
      name: es-custom-config
```
Also as per the kubedb document, I have added spec.monitor.args
`https://kubedb.com/docs/0.10.0/concepts/database-monitoring/overview/`
But when i checked elastic search exporter, I can see it started with only below arguments
```
 Port:          56790/TCP
    Host Port:     0/TCP
    Args:
      --es.uri=http://$(DB_USER):$(DB_PASSWORD)@localhost:9200
      --web.listen-address=:56790
      --web.telemetry-path=/metrics
```
As Discussed with @hossainemruz , elastic search statefulset is missing the code to append supplied arguments.
https://github.com/kubedb/elasticsearch/blob/27a27b04a9569b0d64f47f5ca8f79c44b16b685f/pkg/controller/statefulset.go#L487

while redis has correct implementation,
https://github.com/kubedb/redis/blob/61417d3f1ca5a840dee9a71aa8fd58ce8bfaaabd/pkg/controller/statefulset.go#L283
