### ISSUE TITLE
mongodb liveness/readiness probes connect without authentication

### ISSUE THREAD

**Issue by blushingpenguin** [kubedb/project#609]
trying the example from 
https://kubedb.com/docs/0.12.0/guides/mongodb/clustering/replicaset/

019-08-01T06:00:57.200+0000 I ACCESS   [conn493] Unauthorized: not authorized on admin to execute command { endSessions: [ { id: UUID("2d2b098f-7a02-4b84-9e42-d6f6fa1cad39") } ], $db: "admin" }
2019-08-01T06:00:57.201+0000 I NETWORK  [conn493] end connection 127.0.0.1:40296 (10 connections now open)
2019-08-01T06:01:01.507+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:40342 #494 (11 connections now open)
2019-08-01T06:01:01.508+0000 I NETWORK  [conn494] received client metadata from 127.0.0.1:40342 conn494: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.6.12" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "16.04" } }

and:

mark@theology:~/dev$ kubectl get -n demo mongodb.kubedb.com/mgo-replicaset -o yaml
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  creationTimestamp: "2019-08-01T05:21:39Z"
  finalizers:
  - kubedb.com
  generation: 3
  name: mgo-replicaset
  namespace: demo
  resourceVersion: "1123309"
  selfLink: /apis/kubedb.com/v1alpha1/namespaces/demo/mongodbs/mgo-replicaset
  uid: 3d2ec6f0-b41c-11e9-ae28-822fedf9a955
spec:
  certificateSecret:
    secretName: mgo-replicaset-keyfile
  databaseSecret:
    secretName: mgo-replicaset-auth
  podTemplate:
    controller: {}
    metadata: {}
    spec:
      livenessProbe:
        exec:
          command:
          - mongo
          - --eval
          - db.adminCommand('ping')
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        exec:
          command:
          - mongo
          - --eval
          - db.adminCommand('ping')
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources: {}
      securityContext:
        fsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
  replicaSet:
    name: rs0
  replicas: 3
  serviceTemplate:
    metadata: {}
    spec: {}
  storage:
    accessModes:
    - ReadWriteOnce
    dataSource: null
    resources:
      requests:
        storage: 1Gi
  storageType: Durable
  terminationPolicy: Pause
  updateStrategy:
    type: RollingUpdate
  version: 3.6-v3
status:
  observedGeneration: 3$4212299729528774793
  phase: Running

seems like the generated config is mismatched (mongo is set to use authentication, the probe is not).

**Comment by the-redback** [comment]
The `ping` passes without authentication. So, we kept it that way. 
But, the error messages can be misleading for users. 

So, we can introduce authentication for `ping` probes.

**Comment by blushingpenguin** [comment]
Ok, I hadn't released it was succeeding.

```
      podTemplate:
        spec:
          env:
          livenessProbe:
            exec:
              command:
              - bash
              - "-c"
              - |
                mongo -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --eval db.adminCommand\(\"ping\"\)
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - bash
              - "-c"
              - |
                mongo -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --eval db.adminCommand\(\"ping\"\)
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
```

is what I did to work around it (might help somebody else looking for the error messages).
