### ISSUE TITLE
Add possibility to set custom annotations in Elasticsearch topology

### ISSUE THREAD

**Issue by paweloczadly** [kubedb/project#618]
Hi,

It would be so cool, if a user could specify custom annotations in [Elasticsearch object](https://github.com/kubedb/apimachinery/blob/master/apis/kubedb/v1alpha1/elasticsearch_types.go#L114) for master, client and data. 

I mean something like this:

```
apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: ops-elasticsearch
spec:
  version: 6.5.3
  storageType: Durable
  topology:
    master:
      prefix: master
      replicas: 1
      annotations:
        key1: value1
        key2: value2
```

Then the stateful set would create pods with all specified annotations.
