### ISSUE TITLE
Snapshot to multiple directories

### ISSUE THREAD

**Issue by rblaine95** [kubedb/project#624]
Hi there

I was wondering if it's possible to have a scheduled backup write to multiple directories or storage mediums.

For example, to have a single snapshot backup to S3, GCS, and Local PVC:
```yaml
backupSchedule:
  cronExpression: "@every 10m"
  storageSecretName: kubedbStorageSecret

  s3:
    bucket: kubedb-snap
    endpoint: http://minio.svc:8080/

  local:
    mountPath: /repo
    persistentVolumeClaim:
      claimName: snap-pvc

  gcs:
    bucket: kubedb-snap
```
```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgres
  name: kubedbStorageSecret
data:
  AWS_ACCESS_KEY_ID: "****"
  AWS_SECRET_ACCESS_KEY: "****"
  GOOGLE_PROJECT_ID: "****"
  GOOGLE_SERVICE_ACCOUNT_JSON_KEY: "****"
type: Opaque
```
#### Environment:
```sh
$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://example.net:8443
openshift v3.11.0+3b2d3b6-227
kubernetes v1.11.0+d4cacc0
```
KubeDB Operator Version: `0.12.0`

#### Extra?
Is there a config that can be set so that KubeDB will only keep `x` number of Snapshots and delete older snapshots automatically?
