### ISSUE TITLE
MySQL: Unable to login into mysql instance with custom databaseSecret

### ISSUE THREAD

**Issue by johannwagner** [kubedb/project#643]
Hey,

I tried to create a MySQL instance with a custom databaseSecret on a kubernetes cluster. After creation, I am not able to login into the database.

I execed into the container, the environment variables are properly set and correct. I can't login into the database from within the container.

Spec:

```
apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: wordpress-kubedb-mysql
  namespace: production
spec:
  version: "8.0.14"
  databaseSecret:
    secretName: wordpress-kubedb-mysql-secret
  storageType: Durable
  storage:
    storageClassName: "storage-ceph-ssd"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  terminationPolicy: DoNotTerminate

---

apiVersion: v1
kind: Secret
metadata:
  name: wordpress-kubedb-mysql-secret
  namespace: production
type: Opaque
data:
  user: cm9vdAo=
  password: TGFpbjRlaXhlZQo=
```

Credentails are not in production, so this is fine.

Environment in Container: 

```
root@wordpress-kubedb-mysql-0:/# env | grep MYSQL
MYSQL_ROOT_PASSWORD=Lain4eixee
MYSQL_MAJOR=8.0
MYSQL_ROOT_USERNAME=root
MYSQL_VERSION=8.0.14-1debian9
```
