### ISSUE TITLE
Mongo backup job without PVC cause panic

### ISSUE THREAD

**Issue by xing0821** [kubedb/project#645]
sharding yaml :
```
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mongo-sh
  namespace: demo
spec:
  version: 3.6-v3
  storageType: Ephemeral
  terminationPolicy: WipeOut
  monitor:
    agent: coreos-prometheus-operator/builtin
  serviceTemplate:
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: "56790"
      prometheus.io/scrape: true
  shardTopology:
    configServer:
      replicas: 3
    mongos:
      replicas: 2
      strategy:
        type: RollingUpdate
    shard:
      replicas: 3
      shards: 3
```

snapshot yaml:
```
apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: snapshot-instant
  namespace: demo
  labels:
    kubedb.com/kind: MongoDB
spec:
  databaseName: mongo-sh
  storageSecretName: mg-snap-secret
  s3:
    bucket: operator-test
    endpoint: 'http://private.oss.com'
    prefix: "mongo-test"
```

stracktrace : 
```
E0919 06:16:20.022742       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 627 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x23e2180, 0x6c4d1f0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
kubedb.dev/mongodb/pkg/controller.snapshotStorageSize(0xc000286580, 0xe)
	/src/vendor/kubedb.dev/mongodb/pkg/controller/job.go:395 +0x58
kubedb.dev/mongodb/pkg/controller.(*Controller).getSnapshotterJob(0xc0006056c0, 0xc000300580, 0xc0016928a0, 0x2726c2c, 0xc0016926f0)
	/src/vendor/kubedb.dev/mongodb/pkg/controller/job.go:231 +0x1f2a
kubedb.dev/mongodb/pkg/controller.(*Controller).GetSnapshotter(0xc0006056c0, 0xc000300580, 0xc00124e010, 0xe, 0x0)
	/src/vendor/kubedb.dev/mongodb/pkg/controller/snapshot.go:66 +0x35
...
```

the code that cause panic
```
	topology := db.Spec.ShardTopology
	if topology != nil {
		stg := topology.Shard.Storage
		stgSizePtr := stg.Resources.Requests[core.ResourceStorage]
```

NOTE : topology.Shard.Storage could be empty pointer here
And : If the storage type is Ephemeral, can we just ignore the pvc and use emptydir ?
