### ISSUE TITLE
Default arg (redis.conf path) getting added in the end of args list when extra args are provided for redis-server

### ISSUE THREAD

**Issue by kalpanathanneeru** [kubedb/project#648]
Below is a snippet of the Redis CRD spec. I have added two extra args under spec.podTemplate.spec, as below:
```
apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis
spec:
  podTemplate:
    spec:
      args:
      - --cluster-announce-ip
      - $(POD_IP)
```
When I create the above CRD, the redis statefulset is getting created with the extra args in the first of the args list and the default arg (path to redis.conf) is getting added in the end of the args list, as shown below:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-shard0
spec:
  template:
    spec:
      containers:
      - args:
        - --cluster-announce-ip
        - $(POD_IP)
        - /usr/local/etc/redis/redis.conf
        env:
          - name: POD_IP
 ```
Note: values of other fields have been omitted for brevity.

However, redis-server accepts its args like below:
```
 # redis-server --help
Usage: ./redis-server [/path/to/redis.conf] [options]
       ./redis-server - (read config from stdin)
       ./redis-server -v or --version
       ./redis-server -h or --help
       ./redis-server --test-memory <megabytes>
```
So, for the above CRD, redis-server is being run like below:
```
# redis-server cluster-announce-ip <ip_addr> /usr/local/etc/redis/redis.conf
```
As redis-server expects its first argument to be the path to redis.conf, the below error is being thrown while container starts up:
```
 Fatal error, can't open config file 'cluster-announce-ip'
```
As per the code, default arg is being added to the args list in the end when extra args are being provided.
https://github.com/kubedb/redis/blob/0bbe331944c955542b57e3c7b0fcd542c9d0275b/pkg/controller/statefulset.go#L421
