### ISSUE TITLE
Postgres upgrade handling with KubeDB

### ISSUE THREAD

**Issue by stephan2012** [kubedb/project#654]
Just tested to upgrade an existing Postgres 9.6 database to 11.2 by patching `.spec.version` in the Postgres object which ended in active and hotstandby instances failing with

```
2019-10-01 13:52:11.748 UTC [17] DETAIL:  The data directory was initialized by PostgreSQL version 9.6, which is not compatible with this version 10.6.
```

#374 suggests that Postgres release upgrades are not yet handled by KubeDB (currently using 0.12). What is meanwhile the recommended way of upgrading Postgres in a KubeDB compatible way until KubeDB can do it automatically? Did not find any helpful docs on this topic.

**Comment by strigona-worksight** [comment]
I believe the workflow is: backup your database, create a new instance of Postgres running the newer version and then restore your backup.

**Comment by victorjatoba** [comment]
I have the same problem trying to update version: "10.2-v4" to "11.2":

```
FATAL:  database files are incompatible with server
DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 11.1
```

**Comment by victorjatoba** [comment]
I solved my problem updating to **11.2** version

```
...
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres
  namespace: <%- namespace %>
spec:
  version: "11.2"
...
```
