### ISSUE TITLE
deployment with terraform

### ISSUE THREAD

**Issue by pmpetit** [kubedb/project#655]
using terraform to deploy kubedb postgresql operator, i face an issue : 
```
Warning  Unhealthy  4s (x3 over 24s)  kubelet, gke-retail-h2-pr-retail-h2-pr-np1-f78932af-4j2n  Readiness probe failed: Get https://10.41.180.19:8443/healthz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  2s                kubelet, gke-retail-h2-pr-retail-h2-pr-np1-f78932af-4j2n  Liveness probe failed: Get https://10.41.180.19:8443/healthz: net/http: TLS handshake timeout
```
to reproduce the problem : 
create a main.tf file with
```
data "helm_repository" "kubedb" {
  name = "kubedb"
  url  = "https://charts.appscode.com/stable"
}

resource "helm_release" "kubedb-operator" {
  name = "kubedb-operator"
  repository = "${data.helm_repository.kubedb.name}"
  chart = "kubedb"
  namespace = "kubedb-system"
}

resource "helm_release" "kubedb-catalog" {
  name = "kubedb-catalog"
  repository = "${data.helm_repository.kubedb.name}"
  chart = "kubedb-catalog"
  namespace = "kubedb-system"
}
```
terraform apply

if i disable the  apiserver.healthcheck with:
```
resource "helm_release" "kubedb-operator" {
  name = "kubedb-operator"
  repository = "${data.helm_repository.kubedb.name}"
  chart = "kubedb"
  namespace = "kubedb-system"
  set {
    name  = "apiserver.healthcheck.enabled"
    value = "false"
  }
}
```
then i can  deploy the operatoi without any errors.

Is it possible to put variable here initialDelaySeconds & timeoutSeconds in deployment.yaml
```
        {{- if .Values.apiserver.healthcheck.enabled }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 15
          {{- end }}
```
thanks
