### ISSUE TITLE
Percona-XtraDB failed to start

### ISSUE THREAD

**Issue by shudipta** [kubedb/project#666]
I used the following statefulset for deploying percona-xtradb:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-px-gvr
spec:
  selector:
    app: px
  ports:
    - port: 3306
  type: ClusterIP
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: px
  name: my-px1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: px
  serviceName: my-px-gvr
  template:
    metadata:
      labels:
        app: px
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_ROOT_USERNAME
          value: "root"
        - name: "CLUSTER_NAME"
          value: px
#        - name: "PXC_SERVICE"
#          value: "my-px-gvr"
        image: alittleprogramming/percona-xtradb-cluster:5.7-mysql-user
#        image: alittleprogramming/percona-xtradb-cluster:5.7-mysql-user-non-root
#        image: alittleprogramming/percona-xtradb-cluster:5.7-mysql-user-non-root-everywhere
#        image: alittleprogramming/percona-xtradb-cluster:5.7-percona
#        image: alittleprogramming/pxc-57-try:0
        imagePullPolicy: IfNotPresent
#        imagePullPolicy: Always
        name: px
        command:
        - peer-finder
        args:
          - "-service=my-px-gvr"
          - "-on-start=/on-start.sh"
        ports:
        - containerPort: 3306
          name: db
          protocol: TCP
        - containerPort: 4567
          name: sst
          protocol: TCP
        - containerPort: 4568
          name: replication
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      initContainers:
      - command:
        - rm
        - -rf
        - /var/lib/mysql/lost+found
        image: kubedb/busybox
        imagePullPolicy: IfNotPresent
        name: remove-lost-found
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      restartPolicy: Always
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Mi
      storageClassName: standard

```
