### ISSUE TITLE
Postgres DB can't be created if pod is running with other user than root

### ISSUE THREAD

**Issue by Hi-Fi** [kubedb/project#676]
Using following yaml with KubeDB deployed to both minikube and full Kubernetes cluster (1.15.5 and 1.16.0 versions):
```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres-ephemeral
  namespace: demo
spec:
  version: "11.1"
  storageType: Ephemeral
  podTemplate:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 7357
```

Database fails to start, as it tries to change owner of `$PGDATA` (by default `/var/pv`), and that directory is only writeable by root in container.

When running container with docker and starting only bash, directory rights are:
```
bash-4.4# ls -ld /var/pv/
drwxr-xr-x    2 root     root          4096 Oct 25 10:49 /var/pv/
```
When database is started with root rights, that directory gets following rights:
```
bash-4.4# ls -ld /var/pv/
drwxrwxrwx    3 postgres postgres      4096 Oct 25 10:45 /var/pv
```

According to starter script it should be possible to run DB without root rights, but because of that chown it's currently not.
