### ISSUE TITLE
Enable PMEM storage in Memcached

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#690]
https://kubernetes.slack.com/archives/C8149MREV/p1574158081196600

**Comment by pohly** [comment]
Using memcached with PMEM has benefits that are explained best in https://memcached.org/blog/persistent-memory/.

This can be used in different ways:
1. ephemeral storage (= DRAM replacement): memcached always starts up with an empty cache and then just uses PMEM instead of DRAM to store data
2. restartable cache: on a clean shutdown (= SIGUSR1), it stores some meta data and then when restarted, will use previously stored data

As pointed out in the blog post, using a restartable cache is only suitable if the app using memcached can tolerate getting stale data. So it would have to be a configuration option in the memcached CRD.

Right now, both approaches can be implemented via a PVC that uses PMEM-CSI (https://github.com/intel/pmem-csi) to provision volumes on local PMEM. In both cases, the `-e` option and potentially a fixed memory size `-m` would have to be added to the memcached command line (https://github.com/memcached/memcached/wiki/WarmRestart). The difference then is how memcached gets shut down (or at least that's my understanding - I haven't actually tried it myself). Sending SIGUSR1 might be a bit tricky (run it with an optional wrapper that turns the normal Kubernetes SIGTERM into SIGUSR1?). IMHO it makes sense to focus on the first use case first.

Once PMEM-CSI has created a PV, memcached instances using that PV will only be able to run on that one host. That's not ideal for the ephemeral use case because existing data in that PV will be ignored anyway, so this is an unnecessary limitation. A better alternative are inline ephemeral volumes (https://kubernetes-csi.github.io/docs/ephemeral-local-volumes.html). They are going to be supported in PMEM-CSI 0.6 (code is already in master). But they have several disadvantages right now:
- only became beta in 1.16, alpha in 1.15: older Kubernetes will have to use normal PVCs
- no tracking of available storage: a memcached pod may get scheduled to a node which then doesn't have enough storage, in which case it will fail to come up

I am working on adding this capacity tracking, but it'll depend on changes in Kubernetes, so this will take a while to make it work reliably. The KEP is currently pending: https://github.com/kubernetes/enhancements/pull/1353. I suggest to focus on normal PVCs initially.

The memcached pods are allowed to run on the same node, right? At least the ones from the tutorial don't have any anti-affinity. Is that configurable for a high-availability mode?

In that case, PVCs should use a storage class with `WaitForFirstConsumer`. Otherwise we can have the following situation:
- all PVs get created on the same node
- pods are spread out over different nodes
=> only one of the memcached instances can start

Because memcached doesn't actually need `MAP_SYNC`, this can all be tested with a PVC provided by some other storage system. If you want to test with PMEM-CSI, a cluster brought up inside QEMU is another option. That's what we use for PMEM-CSI itself (https://github.com/intel/pmem-csi/blob/devel/README.md#qemu-and-kubernetes).

**Comment by pohly** [comment]
> Is that configurable for a high-availability mode?

It is, by setting `podTemplate.spec.affinity`:
```
apiVersion: kubedb.com/v1alpha1
kind: Memcached
metadata:
  name: memcd-quickstart
  namespace: demo
spec:
  replicas: 3
  version: "1.5.4-v1"
  podTemplate:
    spec:
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 250m
          memory: 64Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "kubedb.com/name"
                    operator: In
                    values:
                    - memcd-quickstart
              topologyKey: "kubernetes.io/hostname"
  terminationPolicy: Pause
```

This is just a matter of documentation, no special handling of this should be necessary in the operator.
