### ISSUE TITLE
ServiceMonitor matchLabels are not updated with corresponding service update

### ISSUE THREAD

**Issue by Akhalaka** [kubedb/project#701]
Found using v0.12.0 kubedb operator and a postgres database.
After updating a label on a postgreses.kubedb.com object, the underlying stats service object is updated but the ServiceMonitor retains its old value.

Steps to reproduce:
- Create a simple postgres database with a label and monitoring using coreos-operator:
```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  labels:
    foo: bar
  name: mytest
  namespace: kubedb-test
spec:
  replicas: 1
  version: 11.2
  standbyMode: Warm
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      namespace: kubedb-test
      port: 56790
  storageType: Ephemeral
  terminationPolicy: WipeOut
```
- Validate that prometheus has a target for the serviceMonitor.
- `kubectl edit pg mytest` and change the label to `foo: baz`
- After applying the above change the target in prometheus will have 0 targets for the serviceMonitor

Examination shows that the serviceMonitor's matchLabels still contains `foo: bar` and hence does not match any services.

This issue may need a child over in https://github.com/kmodules/monitoring-agent-api as it appears that the agent code lives here.  It looks like the code to update the matchLabels exists, but nothing is setting update to true for this update case when the service labels change.
