### ISSUE TITLE
MySQL Upgrade Failing

### ISSUE THREAD

**Issue by hossainemruz** [kubedb/project#772]
All members get updated successfully but the final status of the `MySQLOpsRequest` become `Failed`. It seems that the enterprise operator is trying to get an outdated member.

```yaml
Name:         myopsreq-group
Namespace:    demo
Labels:       <none>
Annotations:  API Version:  ops.kubedb.com/v1alpha1
Kind:         MySQLOpsRequest
Metadata:
  Creation Timestamp:  2020-06-25T11:41:39Z
  Finalizers:
    mysql.ops.kubedb.com
  Generation:        3
  Resource Version:  8503
  Self Link:         /apis/ops.kubedb.com/v1alpha1/namespaces/demo/mysqlopsrequests/myopsreq-group
  UID:               78837b97-67ae-4fe7-8d6f-57e314c98ab0
Spec:
  Database Ref:
    Name:                my-group
  Stateful Set Ordinal:  1
  Type:                  Upgrade
  Upgrade:
    Target Version:  8.0.20
Status:
  Conditions:
    Last Transition Time:  2020-06-25T11:41:39Z
    Message:               The controller has started to Progress the OpsRequest
    Observed Generation:   1
    Reason:                OpsRequestOpsRequestProgressing
    Status:                True
    Type:                  Progressing
    Last Transition Time:  2020-06-25T11:41:39Z
    Message:               MySQLOpsRequestDefinition: myopsreq-group for Pausing MySQL: demo/my-group
    Observed Generation:   1
    Reason:                PausingDatabase
    Status:                True
    Type:                  PausingDatabase
    Last Transition Time:  2020-06-25T11:41:39Z
    Message:               MySQLOpsRequestDefinition: myopsreq-group for Paused MySQL: demo/my-group
    Observed Generation:   1
    Reason:                PausedDatabase
    Status:                True
    Type:                  PausedDatabase
    Last Transition Time:  2020-06-25T11:41:39Z
    Message:               MySQLOpsRequestDefinition: myopsreq-group for Upgrading MySQL version: demo/my-group
    Observed Generation:   1
    Reason:                OpsRequestUpgradingVersion
    Status:                True
    Type:                  UpgradingVersion
    Last Transition Time:  2020-06-25T11:48:51Z
    Message:               dial tcp: lookup my-group-0.my-group-gvr.demo on 10.96.0.10:53: no such host
    Observed Generation:   2
    Reason:                OpsRequestReconcileFailed
    Status:                False
    Type:                  Failure
    Last Transition Time:  2020-06-25T11:49:00Z
    Message:               MySQLOpsRequestDefinition: myopsreq-group for image successfully upgraded for MySQ: demo/my-group
    Observed Generation:   1
    Reason:                OpsRequestUpgradedVersion
    Status:                True
    Type:                  UpgradedVersion
  Observed Generation:     3
  Phase:                   Failed
Events:
  Type     Reason           Age    From                        Message
  ----     ------           ----   ----                        -------
  Normal   Pausing          8m39s  KubeDB Enterprise Operator  MySQLOpsRequestDefinition: myopsreq-group, Pausing MySQL: demo/my-group
  Normal   SuccessfulPause  8m39s  KubeDB Enterprise Operator  MySQLOpsRequestDefinition: myopsreq-group, successfully paused: demo/my-group
  Normal   Starting         8m39s  KubeDB Enterprise Operator  MySQLOpsRequestDefinition: myopsreq-group, Upgrading MySQL images: demo/my-group
  Normal   Successful       6m18s  KubeDB Enterprise Operator  MySQLOpsRequestDefinition: myopsreq-group, image successfully upgraded for Pod: demo/my-group-1-0
  Normal   Successful       3m58s  KubeDB Enterprise Operator  MySQLOpsRequestDefinition: myopsreq-group, image successfully upgraded for Pod: demo/my-group-1-1
  Normal   Successful       98s    KubeDB Enterprise Operator  MySQLOpsRequestDefinition: myopsreq-group, image successfully upgraded for Pod: demo/my-group-1-2
  Warning  Failed           87s    KubeDB Enterprise Operator  Failed to complete operation for MySQLOpsRequestDefinition: "myopsreq-group". Reason: OpsRequestReconcileFailed
  Normal   Successful       78s    KubeDB Enterprise Operator  MySQLOpsRequestDefinition: myopsreq-group, image successfully upgraded for MySQL: demo/my-group

```
