### ISSUE TITLE
Show Elasticsearch Health Status (Red/Yellow/Green) in CRD.status field

### ISSUE THREAD

**Issue by kamolhasan** [kubedb/project#809]
`status`: Health status of the cluster, based on the state of its primary and replica shards. Can be red or green or yellow.

Since the operator is continuously performing status checks from the background health checker, we can keep the track of the original Elasticsearch status.

```yaml
Elasticseach
spec:
status:
  healthStatus: red/green/yellow
```

Benefits:
 - Can be shown from UI
 - Can be shown in the terminal while performing `$ kuebctl get elasticsearch ...`
