### ISSUE TITLE
SearchGuard and OpenDistro security fails if transport certificate have multiple organization(O) 

### ISSUE THREAD

**Issue by kamolhasan** [kubedb/project#816]
```yaml
  tls:
    certificates:
    - alias: transport
      subject:
        organizations:
        - "org1.com"
        - "org2.com"
```
