### ISSUE TITLE
KubeDB Note: Elasticsearch with IPV6

### ISSUE THREAD

**Issue by kamolhasan** [kubedb/project#820]
## Work Environment setup 

```
$ cat /etc/docker/daemon.json
{
  "ipv6": true,
  "fixed-cidr-v6": "2001:db8:1::/64"
}

$ sudo systemctl reload docker

$ cat ~/kind-config.yaml 
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv6
  
$ kind create cluster --config=$HOME/kind-config.yaml
```

## Install Elasticsearch

```yaml
apiVersion: kubedb.com/v1alpha2
kind: Elasticsearch
metadata:
  name: es
  namespace: demo
spec:
  enableSSL: true 
  version: 7.5.2-searchguard
  storageType: Durable
  terminationPolicy: WipeOut
  replicas: 3
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  podTemplate:
    spec:
      env:
      - name: "network.host"
        value: "_eth0:ipv6_"  
```

Need to overwrite the default `network.host` (`0.0.0.0`) env with value `"_eth0:ipv6_"` or `"_global:ipv6_"`.

Notes:
- **kubectl port-forward to the local machine(ipv4) doesn't work**
- **From inside the pod, curl to localhost/[::1] doesn't work**
- **Need to use the pod's IP, to connect to the Elasticsearch using curl, from inside the cluster**

```
$ kubectl get pods -n demo -o wide
NAME   READY   STATUS    RESTARTS   AGE     IP                NODE                 NOMINATED NODE   READINESS GATES
es-0   1/1     Running   0          3m24s   fd00:10:244::69   kind-control-plane   <none>           <none>
es-1   1/1     Running   0          3m15s   fd00:10:244::6b   kind-control-plane   <none>           <none>
es-2   1/1     Running   0          3m1s    fd00:10:244::6e   kind-control-plane   <none>           <none>

$ kubectl exec -it -n demo es-0 -- bash

$ curl -g -XGET -u 'admin:ZL3P4U9vukI$-!Pv' "https://[fd00:10:244::69]:9200/_cluster/health?pretty" -k
{
  "cluster_name" : "es",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 3,
  "number_of_data_nodes" : 3,
  "active_primary_shards" : 5,
  "active_shards" : 11,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}

$ curl -g -XPUT -u 'admin:ZL3P4U9vukI$-!Pv' "https://[fd00:10:244::69]:9200/demo1" -k
{"acknowledged":true,"shards_acknowledged":true,"index":"demo1"}

$ curl -g -XPUT -u 'admin:ZL3P4U9vukI$-!Pv' "https://[fd00:10:244::69]:9200/demo2" -k
{"acknowledged":true,"shards_acknowledged":true,"index":"demo2"}

$ curl -g -XGET -u 'admin:ZL3P4U9vukI$-!Pv' "https://[fd00:10:244::69]:9200/_cat/indices" -k
green open searchguard            l7qBesPzSx2Jo4O1YEa59w 1 2 6 0 83.3kb 32.2kb
green open .signals_settings      lAYqgNRQQketR-Iu8BS0tg 1 1 2 0 23.5kb 17.4kb
green open .signals_watches       yz6lVxezRj-tBf442IPxwQ 1 1 0 0   566b   283b
green open .signals_accounts      kOVALWqrTTaP1Wdag-nb6w 1 1 0 0   566b   283b
green open .signals_watches_state 1Ucotj3cSW6T2A7HDPc4rw 1 1 0 0   566b   283b
green open demo1                  2CS7vlHCR3y3jLkQ9dxC9g 1 1 0 0   460b   230b
green open demo2                  vbbCTMbtSBmWA6w13qHL-w 1 1 0 0   460b   230b
```

Ref:
- https://discuss.elastic.co/t/issues-with-installation-in-ipv6-environment/207000/5
- https://www.elastic.co/guide/en/elasticsearch/reference/7.10/modules-network.html#common-network-settings
