### ISSUE TITLE
Postgres server doesn't seem to start

### ISSUE THREAD

**Issue by astralbijection** [kubedb/project#832]
I've declared the following database, largely copied from the [quickstart guide](https://kubedb.com/docs/0.8.0-beta.0/guides/postgres/overview/):

```yaml
apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: synapse-db
spec:
  version: "13.2"
  replicas: 1
  storageType: Durable
  storage:
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
  terminationPolicy: DoNotTerminate
```

But whenever my pods connect to the database, they get a connection refused error.

I've also tried to connect directly to the database, and initialize it like this:
```
❯ kubectl exec -it synapse-db-0 -- bash
Defaulting container name to postgres.
Use 'kubectl describe pod/synapse-db-0 -n matrix' to see all of the containers in this pod.
bash-5.1$ psql
psql: error: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
bash-5.1$ psql -h localhost
psql: error: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
bash-5.1$ initdb
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /var/pv/data ... initdb: error: could not create directory "/var/pv/data": Permission denied
```

This issue does not occur with MariaDB, only with Postgres. I'm guessing that the database isn't even being started for some reason. What should I do to fix it?
