### ISSUE TITLE
Support user provided annotations

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#85]
```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: xyz
  labels:
    k1: v1
    k2: v2
spec:
  version: 9.6
  replicas: 3

  podTemplate:
    metadata:
      annotations:
        k1: v1
        k2: v2
    spec:
      nodeSelector:
        region: us-east-1
    controller:
      annotations:
        k1: v1
        k2: v2
  serviceTemplate:
    metadata:
      annotations:
        k1: v1
        k2: v2
  backupSheduler:
    s3:
      endpoint:
      bucket:
    podTemplate:
      metadata:
        annotations:
          k1: v1
          k2: v2
      spec:
        nodeSelector:
          region: us-east-1
      controller:
        annotations:
          k1: v1
          k2: v2
---

spec:
	service:
		type: ClusterIP
		annotations:
			k1: v1
		statsServiceAnnotations:
			k1: v1
	workload:
		annotations:
			k1: v1
		podAnnotations:
			k1: v1
--------
labels:
  workload <- statefulset, deployment
  service <-
  stats service
  secret
```
