### ISSUE TITLE
kubedb/schema-manager

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#851]
```
kubebuilder init --domain kubedb.com --skip-go-version-check
kubebuilder edit --multigroup=true
kubebuilder create api --group schema --version v1alpha1 --kind MySQLDatabase --force
kubebuilder create api --group schema --version v1alpha1 --kind RedisDatabase --force
kubebuilder create api --group schema --version v1alpha1 --kind MariaDBDatabase --force
kubebuilder create api --group schema --version v1alpha1 --kind PostgresDatabase --force
kubebuilder create api --group schema --version v1alpha1 --kind MongoDBDatabase --force
```

**Comment by tamalsaha** [comment]
```
- https://github.com/kubevault/demo/tree/master/webinar-10-13-21/deploy
- https://github.com/kubevault/demo/blob/master/webinar-10-13-21/deploy/mongodb.yaml
- https://github.com/kubevault/demo/blob/master/webinar-10-13-21/deploy/secretengine.yaml
- https://github.com/kubevault/demo/blob/master/webinar-10-13-21/deploy/reader-writer-role.yaml
- https://github.com/kubevault/demo/blob/master/webinar-10-13-21/deploy/read-access-request.yaml

apiversion: schema.kubedb.com/v1alpha1
kind: MongoDBDatabase

metadata:
  name: {db-crd-name}-{db-name}
  namespace: {db-user-ns}

spec:
  unmanaged: true
  databaseRef:
    name: {db-crd-name}
    namespace: {db-ns}
  vaultRef:
    name: {name}
    namespace: {namespace}
  db:
    name: {db-name}
    # collatation: 
  subjects:
    - kind: ServiceAccount
      name: readonly-user
      namespace: user-2
  init:
    initialized: true
    script:
    podTemplate:
  deletionPolicy: Delete | DoNotDelete

Reserve Database names
- admin
- config
- kubedb-system

# create a db named kubedb-system
- create a collection schema-manager
- create a document {"db-name": "uid"}

# SecretEngine, db-ns
# MongoDBRole, db-ns 
# SecretAccessRequest , user-ns, auto approve
# Secret, after pparoval
# Using Secret, run init script using Job if any


On Delete, if deletionPolicy == Delete (same as Wipeout )
- MongoDBRole
- SecretAccessRequest
- Secret
- Delete actual db inside Mongo
- Remove document from schema-manager collection

```
