### ISSUE TITLE
Bug with Sealed Secret

### ISSUE THREAD

**Issue by cedvan** [kubedb/project#881]
Hi,

I use Sealed Secret to protect my secrets. (https://github.com/bitnami-labs/sealed-secrets)

KubeDB not wait secret generated by sealed secret and failed on provisionning.
No retry periodicaly, so database stay in provisionning. 
To fix need delete and recreate manually, so it's a real problem with ArgoCD deployment...

#### Sample

*pg-auth.yaml*
```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: pg-auth
    namespace: demo
spec:
    encryptedData:
        POSTGRES_USER: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        POSTGRES_PASSWORD: yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
```

*pg.yaml*
```yaml
apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
    name: pg
    namespace: demo
spec:
    version: "13.6"
    authSecret:
        name: pg-secret
    storageType: Durable
    storage:
        resources:
            requests:
                storage: 5Gi
    terminationPolicy: Delete
```

*kustomization.yaml*
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
     - pg-auth.yaml
     - pg.yaml
```
#### Result

```yaml
NAME   VERSION   STATUS             AGE
pg         13.6             Provisionning    34m
```

```yaml
Status:
  Conditions:
    Last Transition Time:  2022-09-19T09:59:21Z
    Message:               The KubeDB operator has started the provisioning of Postgres: demo/pg
    Reason:                DatabaseProvisioningStartedSuccessfully
    Status:                True
    Type:                  ProvisioningStarted
  Observed Generation:     1
  Phase:                   Provisioning
Events:
  Type     Reason   Age    From             Message
  ----     ------   ----   ----             -------
  Warning  Invalid  7m29s  KubeDB Operator  secrets "pg-auth" not found
```

NB : Same behavior with redis, except auto generate missing secret, but stay in provisionning too.

**Comment by tamalsaha** [comment]
Thanks for the feature request. At the moment you can work around the issue by ensuring the secret is available before the database YAML is applied to the cluster. 

We are going to look into implementing the necessary wait feature for sealed secrets.

**Comment by cedvan** [comment]
But I can't use this alternative, I deploy my resources with ArgoCD.... I don't know how force ArgoCD create sealed secret  before other resources.

This is also the true concept of K8s, not worrying about scheduling and letting K8s manage and (re)try to make it work

**Comment by tamalsaha** [comment]
I understand. We are going to get this implemented in the next release at the end of Sep or early Oct. https://github.com/kubedb/apimachinery/pull/976

**Comment by cedvan** [comment]
I looked the pull request, it allows setting a SealedSecret kind instead of a Secret, but I don't understand this solution. 

Once a Sealed Secret is deployed, a Secret will be generated, so kubeDB should use that secret directly and not reference a sealed secret. 

A solution would be rather not to automatically create the secret if it is missing, and retry start the database indefinitely (every X period) if the secret is missing no ?

**Comment by tamalsaha** [comment]
The plan is that if the user provides a reference to a SealedSecret, then the KubeDB operator will wait until the matching secret is ready before provisioning the statefulsets etc. The `apiGroup` and `kind` will be used to implement the waiting-until-regular-k8s-secret-is-available.

Do you think that addresses the issue you are facing currently?

**Comment by cedvan** [comment]
Yes this solution will be work, but...

This behavior seems risky to me, what happens in the case of a different kind of SealedSecret (example CustomOtherSecret) which generates a secret but with a completely custom name defined by its specs? KubeDB will then wait indefinitely and a new issue will be opened.

Why not just look if the secret exists and wait if it doesn't?

And to allow the automatic generation case, add a `generate: true` option

**Comment by tamalsaha** [comment]
We are updating the spec to be like below:

```
spec:
  authSecret:
    name: "xyz"
    externallyManaged: true # sealed-secret, external-secret, etc.
```
